.travis.yml

Travis fails randomly with `ContextualVersionConflict` on `pip` installed packages. This is an attempt to see if removal of `pip` caching on Travis improves the CI success rate.

Remove pip cache from Travis

---

.travis.yml

The default system `numpy` version on Travis is in conflict with `pyarrow`, failing documentation build and deploy using Travis.
Resolves #22.

Update system `numpy` on Travis

---

.travis.yml
setup.py
tests/test_parameter_distribution.py

Comply with [recent change in `dash`](https://github.com/plotly/dash/blob/master/dash/CHANGELOG.md#101---2019-07-09) wrt. to how test dependencies are installed and tests are written.
In addition:
- Update chrome driver in `.travis.yml` (since Travis has jumped to Chrome version 76).
- Update to _Ubuntu Bionic 18.04_ (from default Travis Ubuntu Trusty 14.04) as that [is now the recommended way of using `xvfb` in Travis](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui).

Dash test dependencies and align with Travis update

---

.pylintrc
webviz_subsurface/containers/_disk_usage.py
webviz_subsurface/containers/_inplace_volumes.py
webviz_subsurface/containers/_intersect.py
webviz_subsurface/containers/_morris_plot.py
webviz_subsurface/containers/_parameter_distribution.py
webviz_subsurface/containers/_summary_stats.py

`pylint` does not recognize that decorated callback functions are used within `dash`, and therefore falsely reports them as unused. This is solved by prefixing them with `_`, which at the same time indicates that these callback functions are defined (and used) within the container.

Prefix callback functions

---

webviz_subsurface/containers/_parameter_distribution.py

Adds config file optional boolean argument `drop_constants` to `ReservoirSimulationTimeSeries`
Default is `True` which will drop all parameters that are not varying.
Fixes  #68 
Also some small styling changes that fixes #62

Optionally visualize non-varying parameters in ParameterDistribution container

---

examples/basic_example.yaml
setup.py
tests/test_parameter_correlation.py
webviz_subsurface/containers/__init__.py
webviz_subsurface/containers/_parameter_correlation.py

The container currently named `ParameterDistribution` is geared more towards showing correlations. Rename.

Rename ParameterDistribution to ParameterCorrelation

---

README.md

Codacy project moved to separate `webviz` project. Update badge link.
[![Codacy Badge](https://api.codacy.com/project/badge/Grade/9fd7a8b451754841a1eb6600c08be967)](https://www.codacy.com/manual/webviz/webviz-subsurface?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=equinor/webviz-subsurface&amp;utm_campaign=Badge_Grade)

Update codacy badge link

---

webviz_subsurface/containers/_disk_usage.py
webviz_subsurface/containers/_history_match.py
webviz_subsurface/containers/_inplace_volumes.py
webviz_subsurface/containers/_intersect.py
webviz_subsurface/containers/_morris_plot.py
webviz_subsurface/containers/_parameter_correlation.py
webviz_subsurface/containers/_parameter_distribution.py
webviz_subsurface/containers/_reservoir_simulation_timeseries.py
webviz_subsurface/containers/_subsurface_map.py
webviz_subsurface/datainput/_fmu_input.py
webviz_subsurface/datainput/_history_match.py
webviz_subsurface/datainput/_inplace_volumes.py
webviz_subsurface/datainput/_intersect.py
webviz_subsurface/datainput/_reservoir_simulation_timeseries.py
webviz_subsurface/datainput/layeredmap/_image_processing.py
webviz_subsurface/datainput/layeredmap/_layered_fence.py
webviz_subsurface/datainput/layeredmap/_layered_surface.py

Group according to PEP8 guide + remove two instances of unused imports.
> Imports should be grouped in the following order:
> 
> 1. Standard library imports.
> 2. Related third party imports.
> 3. Local application/library specific imports.
>
> You should put a blank line between each group of imports.

PEP8 group imports

---

webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

Closes #205  by increasing spacing between items.
The alternative of decreasing font size would require external css overwrite of the `Select-menu-outer` class.

More readable timeseries dropdown

---

tests/integration_tests/test_aggregated_data_example.py
tests/integration_tests/test_raw_data_example.py

When running Selenium tests, sometimes (!) on Travis, an error like
```
TypeError: Cannot read property 'hardwareConcurrency' of undefined
```
appears. Checking what is going on...

Filter dashduo logs in tests

---

webviz_subsurface/plugins/_surface_viewer_fmu.py

Fixed issue when surface calculation failed due to different geometries.
When surface calculation fails view1 and view2 should update, while view3 should be set to empty.

Allow surface updates when geometry differs

---

.travis.yml
setup.py
webviz_subsurface/_datainput/fmu_input.py
webviz_subsurface/plugins/__init__.py
webviz_subsurface/plugins/_running_time_analysis_fmu.py

Closes #51 and #231, replacing #229

Running time analysis FMU

---

.github/workflows/webviz-subsurface.yml

When `webviz` has made a portable application, we can delete the raw data source before bulding the Docker image (in order to decrease the chance of running out of space on the GitHub CI runner).

Delete raw testdata when finished aggregating

---

setup.py
webviz_subsurface/plugins/_segy_viewer.py
webviz_subsurface/plugins/_surface_viewer_fmu.py
webviz_subsurface/plugins/_surface_with_grid_cross_section.py
webviz_subsurface/plugins/_surface_with_seismic_cross_section.py
webviz_subsurface/plugins/_well_cross_section.py
webviz_subsurface/plugins/_well_cross_section_fmu.py

Remove now unnecessary Path → str conversion wrt. xtgeo

---

setup.py
tests/integration_tests/test_aggregated_data_example.py
tests/integration_tests/test_raw_data_example.py
tests/integration_tests/test_surface_selector.py
webviz_subsurface/_private_plugins/surface_selector.py
webviz_subsurface/_private_plugins/tornado_plot.py
webviz_subsurface/plugins/_inplace_volumes_onebyone.py
webviz_subsurface/plugins/_parameter_distribution.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
webviz_subsurface/plugins/_running_time_analysis_fmu.py
webviz_subsurface/plugins/_surface_viewer_fmu.py
webviz_subsurface/plugins/_well_cross_section_fmu.py

Closes #317 
Fixes related to Dash 1.11.
- We used some wrong component props in callbacks that are no longer allowed in Dash 1.11. E.g. `dcc.Store(children)` should be `dcc.Store(data)`.
- There is a breaking change in Dash 1.11 when using `callback_context.triggered`. It is no longer possible to identify which input parameters triggers the first time a callback is executed. A check for this has been added to the necessary callbacks.

Support Dash 1.11

---

webviz_subsurface/_abbreviations/abbreviation_data/reservoir_simulation_unit_terminology.json
webviz_subsurface/_abbreviations/abbreviation_data/volume_terminology.json
webviz_subsurface/_abbreviations/number_formatting.py
webviz_subsurface/_abbreviations/reservoir_simulation.py
webviz_subsurface/_datainput/fmu_input.py
webviz_subsurface/_utils/simulation_timeseries.py
webviz_subsurface/plugins/_inplace_volumes.py
webviz_subsurface/plugins/_inplace_volumes_onebyone.py
webviz_subsurface/plugins/_parameter_response_correlation.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py

Resolves #284. 
The "more robust vector vs node name split" was not done, as it seems like `fmu_ensemble`/`libecl` doesn't support all the properties of vector names that we use (especially for region keywords). Think our existing solution is the best we could hope for atm.
Some improvements have also been made to the vector type identification (`is_rate`/`is_total`) [upstream in libecl](https://github.com/equinor/libecl/pull/707).  but the code is not dependent on these changes. 
Will also improve the `is_historical` flag when [this issue is completed ](https://github.com/equinor/libecl/issues/708). Should be pretty straight forward as long as we get the ideas "approved".
Since a lot of the modifications were related to vectors and units, I tried to keep #296 in the back of my head. …

Simulation metadata

---

setup.py
webviz_subsurface/plugins/_inplace_volumes.py
webviz_subsurface/plugins/_inplace_volumes_onebyone.py
webviz_subsurface/plugins/_parameter_correlation.py
webviz_subsurface/plugins/_parameter_parallel_coordinates.py
webviz_subsurface/plugins/_parameter_response_correlation.py
webviz_subsurface/plugins/_running_time_analysis_fmu.py

- For selectors with multiple options it is more user friendly to use wcc.Select instead of dcc.Dropdown in some cases.
- Fix layout after flexbox
Closes #320

Use wcc.Select instead of dcc.Dropdown

---

.github/workflows/webviz-subsurface.yml

`fmu-ensemble` (temporarily) do not list `libecl` as a dependency now. Install it "manually" also in the Dockerfile.

Add libecl in Docker

---

.github/workflows/webviz-subsurface.yml
README.md

A review of `webviz-subsruface` PRs currently typically consists of two steps:
- Review the actual code changes
- Fetch the PR locally, install the changes, and run an example application to see front-end changes.
The second step is unnecessary time-consuming. In this pull request, we try to facilitate automatic deployment of an example docker image, whenever the PR gets a commit with commit message including the substring `[deploy test`].

Facilitating deployment of "review images"

---

.github/workflows/webviz-subsurface.yml

Now that we have use cases for building the Docker example image also not only on push to `master`, we want to make sure the relevant code state of `webviz-subsurface` is installed.

Install correct webviz-subsurface in Docker example when from PRs

---

webviz_subsurface/_abbreviations/number_formatting.py
webviz_subsurface/_private_plugins/tornado_plot.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py

Resolves #327 and resolves #339
Done in the same PR as it felt a bit more efficient.
Also some necessary modifications to `TornadoPlot` and a minor change to `number_formatting.py` (a bug spotted on the way in the case that `locked_si_prefix==0`, could be a separate PR).
- History traces added. Added with black color, but slightly thicker than default. Not ideal, but didn't want to make something that was very specific for a `theme`. Open for suggestions there.
- Legends added to time series
- Time series coloring is now correctly updated both on click and change of vector. To make it possible:
- In `TornadoPlot`, a storage is now created for realizations for each sensitivity in the whole `TornadoPlot`, and not just the sensitivities that are clicked on. The click storage in …

Improvements of ReservoirSimulationTimeSeriesOneByOne

---

.github/workflows/webviz-subsurface.yml

GitHub action Python images are a bit unpredictable. Suddenly the Python 3.7 image started having pre-installed versions of some packages (which then changed which versions of our dependencies where later installed).
Wipe pre-installed Python packages if any exist.

Clean Python GitHub action setup

---

webviz_subsurface/_utils/simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

Resolves #276 and #326 (though only download, not table).
Adds functionality to download visualized data from the ReservoirSimulationTimeseries plugin. Data is stored in a zipped folder
as a csvfile.
The code has been somewhat refactored to ease the download functionality + to make the code more modular and reusable.
Some simple performance tests indicate that the new solution is at least not slower than the previous (if anything slightly faster).
Supports:
Some data is intentionally currently not supported for download, as they are not part of the basic dataframe which is exported to csv (they would require custom solutions which I haven't prioritized). Think this PR is useful without them. This includes (at least):

Download data from ReservoirSimulationTimeseries

---

webviz_subsurface/plugins/_surface_viewer_fmu.py
webviz_subsurface/plugins/_well_cross_section_fmu.py

Closes #384 (hopefully).
After [this `xtgeo` commit](https://github.com/equinor/xtgeo/pull/369/files#diff-c8c9bc2052a264d274e4099549de0e0fR2555-R2629), `surface_instance.values = some_value` does not set the `values` property if `some_value` is not of one of the expected types (and is ignored silently).
Explicitly cast to `np.array` to support `xtgeo >= 2.9.0`.

Work-around xtgeo.RegularSurface values initialization

---

tests/unit_tests/data_input/test_calc_from_cumulatives.py
tests/unit_tests/utils_tests/test_simulation_timeseries.py
webviz_subsurface/_abbreviations/reservoir_simulation.py
webviz_subsurface/_datainput/from_timeseries_cumulatives.py
webviz_subsurface/_utils/simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

Closes #292 
The PR covers statistically averaged rates (per day) for a time period calculated from cumulative (total) vectors (In the petroleum industry commonly known as `calendar day rates`). 
In addition the delta production per time interval can be shown, which of course is the equivalent of a rate with the interval length as time unit.
To make it performant on-the-fly, only resampling is supported, not interpolation/extrapolation, meaning that the intervals have to be the same or a coarser interval than the dataset, and that the dataset has to be on a recurring frequency. Some modifications to verification of the frequency option part remains, but the plan is to support input frequencies:
- `daily`: with available intervals `daily`, `monthly` and `yearly` (note that `daily` quickly …

Added average rates and cumulatives over specific time interval to ReservoirSimulationTimeSeries

---

CHANGELOG.md
webviz_subsurface/_datainput/history_match.py

Filter on ERT OK file in HistoryMatch

---

.github/workflows/subsurface.yml

It is useful to be able to see e.g. `DeprecationWarning`s in the CI log.
This change will make sure we get all warnings (except those filtered away by code using e.g. `filterwarnings`).

Show all Python warnings in CI log

---

CHANGELOG.md
webviz_subsurface/plugins/_surface_viewer_fmu.py

Suppress numpy warnings from surface calculations

---

CHANGELOG.md
webviz_subsurface/_datainput/surface.py
webviz_subsurface/plugins/_surface_viewer_fmu.py
webviz_subsurface/plugins/_surface_with_grid_cross_section.py
webviz_subsurface/plugins/_surface_with_seismic_cross_section.py

Improve map hillshading and color scale

---

CHANGELOG.md
webviz_subsurface/plugins/_disk_usage.py

Adds free space and puts pie chart and bar chart into the same view for `DiskUsage`.
---
- ~~[ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.~~

Add free space and new design to DiskUsage

---

CHANGELOG.md
webviz_subsurface/_datainput/surface.py

As this is a repo for subsurface containers, the default should maybe be to assume depth data, not elevation?
The demo is currently showing dark colors for shallow areas and bright colors for deep areas. The hillshading is also wrong as it is calculated as elevation.
If you want to use hillshading for other surfaces (e.g. isochores) you would have to revert to a positive elevationScale.
---

Improve depth data defaults for make_surface_layer()

---

CHANGELOG.md
webviz_subsurface/__init__.py

Check if scratch ensemble is empty

---

setup.py

This is related to changes in `webviz-config` - which going forward will use `Download` URL to automatically include required plugin projects in Docker file.
While first doing this - also adding link to documentation and issue tracker.

Add project_urls in setup.py

---

tests/integration_tests/test_aggregated_data_example.py
tests/integration_tests/test_raw_data_example.py

See https://github.com/plotly/dash/issues/1164 for details.
`webviz-subsurface` started seeing this recently when we moved from multi-page app using `dcc.Links`/`dcc.Location` combo instead of `dcc.Tabs`.
We instead ignore `NoSucElementException` and `StaleElementException`, and instead use what the user expects to happen: Selenium raises a `selenium.common.exceptions.TimeoutException` if no working element reference found within the timeout.
---

Dash testing fixture does not handle StaleElementReferenceException

---

CHANGELOG.md
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

Note that in the case of different ensemble sizes, only matching realization indices will be kept (no other logical way to handle it as far as I know).

Drop NaN in delta profiles instead of replacing with zeros

---

.github/workflows/subsurface.yml

...due to recent release of `ecl2df` (today) has a new requirement `equinor-libres` requiring Docker base image to be updated (`gcc` required).

Pin ecl2df in Docker CI

---

CHANGELOG.md
webviz_subsurface/_models/ensemble_model.py

Obeys selected `column_keys` when using `time_index` / `sampling` of `raw` (or the equivalent `None`) when loading and storing `UNSMRY` data.
Did some test on larger datasets than our test data, and it was a dramatic improvement. Saw peak memory usage reduced by up to **97%!**
Nevertheless, it is clear that we have memory issues: with this edit on my larger data set, peak memory usage during load and portable build was still more than 3 times higher than peaks when running the portable. 
**Could also be that we should do the same for `daily` data frequency, as that is also quite high when it comes to reservoir simulation?**
---

Obey column_keys when storing unsmry data with frequency raw

---

CHANGELOG.md
webviz_subsurface/_datainput/surface.py
webviz_subsurface/plugins/_surface_viewer_fmu.py

Minor fixes to SurfaceViewerFMU

---

tests/unit_tests/model_tests/test_ensemble_set_model.py

Use the actual `testdata_folder` argument instead of hard-wired path string in test.
This PR closes #530

Fixed failing test when running with non-default testdata-folder

---

CHANGELOG.md
setup.py
tests/integration_tests/test_parameter_corr.py
webviz_subsurface/_private_plugins/tornado_plot.py
webviz_subsurface/plugins/_assisted_history_matching_analysis.py
webviz_subsurface/plugins/_bhp_qc.py
webviz_subsurface/plugins/_disk_usage.py
webviz_subsurface/plugins/_history_match.py
webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py
webviz_subsurface/plugins/_inplace_volumes.py
webviz_subsurface/plugins/_inplace_volumes_onebyone.py
webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
webviz_subsurface/plugins/_parameter_correlation.py
webviz_subsurface/plugins/_parameter_distribution.py
webviz_subsurface/plugins/_parameter_parallel_coordinates.py
webviz_subsurface/plugins/_parameter_response_correlation.py
webviz_subsurface/plugins/_property_statistics/property_statistics.py
webviz_subsurface/plugins/_pvt_plot.py
webviz_subsurface/plugins/_relative_permeability.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
webviz_subsurface/plugins/_running_time_analysis_fmu.py
webviz_subsurface/plugins/_segy_viewer.py
webviz_subsurface/plugins/_subsurface_map.py
webviz_subsurface/plugins/_surface_viewer_fmu.py
webviz_subsurface/plugins/_surface_with_grid_cross_section.py
webviz_subsurface/plugins/_surface_with_seismic_cross_section.py
webviz_subsurface/plugins/_well_cross_section_fmu.py

Refactor to use new new special `webviz_settings` argument for common settings in favor of the existing solution which piggybacks a dictionary onto the to the Dash applicaton object.
This PR is related to https://github.com/equinor/webviz-config/pull/368 which actually implements the new setting scheme in `webviz-config`.
Bumped the required `webviz-config` version to 0.2.7
---

Use new WebvizSettings instead of dictionary piggybacked onto app object

---

webviz_subsurface/_utils/parameter_response.py
webviz_subsurface/plugins/_parameter_parallel_coordinates.py
webviz_subsurface/plugins/_parameter_response_correlation.py

Reformat `ParameterParallelCoordinates` and `ParameterResponseCorrelation`:
- Simplify removal of duplicate summary data (relates to #553)
- Split out (some) shared code
- Remove caching of functions with `pd.DataFrame` inputs (risky stuff... see #443 )
- Switched out `self.ids` with `self.uuid` for `ParameterResponseCorrelation` (see #554)
---

Reformatting ParameterParallelCoordinates and ParameterResponseCorrelation

---

.github/workflows/subsurface.yml
setup.py
webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
webviz_subsurface/plugins/_property_statistics/models/simulation_timeseries_model.py

This PR implements changes to `SimulationTimeSeriesModel` for both the `ParameterAnalysis` and `PropertyStatistics` plugins. Note that these two plugins do not currently share the model. There exists two relatively similar models.
This PR is related to issue https://github.com/equinor/webviz-subsurface/issues/545 as it resolves some of the underlying issues that causes mutation and/or duplication smry dataframes.
**For `SimulationTimeSeriesModel` in `ParameterAnalysis`:**
Refactored the model to avoid mutating the input smry dataframe and to avoid memory duplication. Removed unused code in preparation for a redesign of the public interface and subsequent consolidation with "near copy" of SimulationTimeSeriesModel that resides within PropertyStatistics.
For now, the part of the public …

Avoid mutating and duplicating smry data in SimulationTimeSeriesModels

---

CHANGELOG.md
webviz_subsurface/_models/surface_leaflet_model.py

Set surface values to zero if all are masked

---

CHANGELOG.md
tests/unit_tests/data_input/test_calc_from_cumulatives.py
webviz_subsurface/_datainput/from_timeseries_cumulatives.py

Set inferred pandas freq = AS-JAN for yearly data

---

.github/workflows/subsurface.yml

Remove `webviz certificate` command from CI, which is not in use after [webviz-config/#374](https://github.com/equinor/webviz-config/pull/374)

Remove webviz certificate from CI

---

CHANGELOG.md
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

No reason to do the calculation at initialisation. Also necessary as follow-up to [webviz-core-components/#99](https://github.com/equinor/webviz-core-components/pull/99) (though that could also be solved by returning `None` rather than `""` when data is not requested).

PreventUpdate in ReservoirSimulationTimeSeries download callback if not data_requested

---

CHANGELOG.md
webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_qc_controller.py
webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
webviz_subsurface/plugins/_parameter_analysis/views/main_view.py
webviz_subsurface/plugins/_parameter_analysis/views/parameter_qc_view.py
webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py

Fixed issue in Parameteranalysis when no `Field` vectors were available.
---

ParameterAnalysis: Allow initialization without field vectors

---

CHANGELOG.md
webviz_subsurface/_utils/simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

Modifications to ReservoirSimulationTimeseries:
- Allow statistical lines without fill (including new P50/median). (Easier to read, avoids overlapping color fills)
- Can choose which statistics to include (Mean, P10, P50, P90, Max, Min)
- Option to remove history trace (and cut history trace at current date, as longer is not realistic even though Eclipse creates it)
- Add `legendgroup` to histogram traces to make them "toggleable"
- Allow histogram together with individual realizations
- Remove history traces in delta plots
---
Technically breaking: `statistics_hist` no longer valid config option (but doubt it is used at all). The default `statistics` now refers to statistical lines, whilst `fanchart` refers to the old default. May consider to change the default to `fanchart`, but I think …

Plot options ReservoirSimulationTimeSeries

---

.github/workflows/subsurface.yml
CHANGELOG.md
setup.py
tests/integration_tests/test_raw_data_example.py
webviz_subsurface/_datainput/well_completions.py
webviz_subsurface/plugins/__init__.py
webviz_subsurface/plugins/_well_completions.py

New plugin WellCompletion for visualizing COMPDAT data from Eclipse.
There are three data sources to this plugin meant to be exported by the FMU workflow:
- a csv file with compdat data
- a lyr file with zone->layer mapping (optional)
- a json file with well attributes (optional)
The plugin aggregates the data to a given format that is passed to the WellCompletions component in webviz-subsurface-components.
---

WellCompletion plugin

---

CHANGELOG.md
setup.py
webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py
webviz_subsurface/plugins/_well_cross_section.py
webviz_subsurface/plugins/_well_cross_section_fmu.py

Add deprecation warning for cross-section plugins

---

CHANGELOG.md
webviz_subsurface/plugins/_well_completions.py

I have fixed some bugs in the docstring and included a tour_steps method

Wrote the tour_steps function and fixed some bugs in the docstring

---

webviz_subsurface/plugins/_relative_permeability.py

Remove SyntaxWarning on Python3.8 in RelativePemerability

---

setup.py
tests/integration_tests/test_parameter_corr.py

`unittest.mock` new in Python 3.3+

Remove `mock` as test requirement

---

CHANGELOG.md
webviz_subsurface/_assets/css/block_options.css
webviz_subsurface/plugins/_assisted_history_matching_analysis.py
webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py
webviz_subsurface/plugins/_relative_permeability.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py

Add back missing `display: block` after https://github.com/equinor/webviz-config-equinor/pull/41.

Add missing `display: block` on selectors

---

CHANGELOG.md
webviz_subsurface/_assets/js/clientside_functions.js
webviz_subsurface/_assets/js/update_plotly_figure.js
webviz_subsurface/plugins/_line_plotter_fmu/controllers/update_figure_clientside.py
webviz_subsurface/plugins/_line_plotter_fmu/line_plotter_fmu.py
webviz_subsurface/plugins/_structural_uncertainty/controllers/intersection_controller.py
webviz_subsurface/plugins/_structural_uncertainty/structural_uncertainty.py

Move existing clientside function to a general dash_clientside file to facilitate adding more functions later on.

Rename clientside functions

---

webviz_subsurface/_utils/simulation_timeseries.py

This fixes a new `mypy` warning which appeared after new release of `types-pyyaml` (7 hours ago): https://pypi.org/project/types-PyYAML/0.1.8/

Fix `mypy` warning with `pyyaml`

---

.github/workflows/subsurface.yml

The CI Docker build works for `upstream` CI since the `Source_URL` in `setup.py` corresponds to that repository https://github.com/equinor/webviz-subsurface/blob/36cd2f5535888d84fc45e394c56ab3b31473f662/setup.py#L96
In order to also work for CI in forks we should override the source URL (i.e. the repository URL) from the `setup.py` according to:
https://github.com/equinor/webviz-config/blob/master/CONTRIBUTING.md#make-your-plugin-project-available

Fix CI deploy from forks

---

webviz_subsurface/_models/surface_leaflet_model.py

Mypy does not identify that either `a_min` or `a_max` can be optional in [numpy.ma.clip.](https://numpy.org/doc/stable/reference/generated/numpy.ma.clip.html)
---

Ignore mypy warning for optional variable in `numpy==1.21`

---

CHANGELOG.md
webviz_subsurface/_components/tornado/_tornado_bar_chart.py
webviz_subsurface/_components/tornado/_tornado_data.py
webviz_subsurface/_components/tornado/_tornado_table.py
webviz_subsurface/_components/tornado/tornado_widget.py
webviz_subsurface/plugins/_inplace_volumes_onebyone.py

Tornado improvements

---

CHANGELOG.md
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

Replaced `dcc.DropDown` with `VectorSelector` for selecting vectors in reservoir simulation timeseries plugin.

Replaced dropdowns with `VectorSelector`

---

tests/integration_tests/test_aggregated_data_example.py
tests/integration_tests/test_raw_data_example.py

While waiting for `webviz-config` `pytest` fixture and/or more modularized tests which probably will make `dash-duo`/`selenium` more stable, we ignore a well known problem that hits the CI by chance/randomly.

Temporary fix flaky tests

---

.github/workflows/subsurface.yml
CHANGELOG.md
setup.py
tests/integration_tests/test_ert_jobs.py
tests/unit_tests/plugin_tests/test_well_completions.py
webviz_subsurface/_datainput/well_completions.py
webviz_subsurface/ert_jobs/config_jobs/EXPORT_CONNECTION_STATUS
webviz_subsurface/ert_jobs/export_connection_status.py
webviz_subsurface/ert_jobs/jobs.py
webviz_subsurface/plugins/_well_completions.py

This PR solves the problem of incomplete compdat OPEN/SHUT history coming from `ecl2df`. There is various problems with `ecl2df `exporting the connection history: it is not picking up lumps of connections being closed by WELOPEN and it could never pick up completions closed with ACTIONS. For history, all the information would be in the schedule file, and it could in theory be solved in ecl2df, but not for predictions with f.ex ACTIONS.
This PR allows the user to pass to the plugin a connection status table, exported by an ERT workflow (EXPORT_CONNECTION_STATUS) for each realization. This data is extracted from the CPI summary data. The data is stored in `.parquet` format and has the following columns: WELL, I, J, K, OP/SH (similar to the ecl2df compdat export: …

`WellCompletion` history from summary data

---

CHANGELOG.md
setup.py
webviz_subsurface/plugins/__init__.py
webviz_subsurface/plugins/_tornado_plotter_fmu/__init__.py
webviz_subsurface/plugins/_tornado_plotter_fmu/tornado_plotter_fmu.py

A plugin to display tornado plots for a csv file with responses from a FMU case with design matrix. 
- Input either as a csv per realization with tabular data, or an aggregated csv_file + a csv file with `SENSNAME` and `SENSCASE` information.
- Columns in csv file can be set as filters, e.g. `DATE` for `UNSMRY` data, or `ZONE` / `REGION` for inplace volume data.
---

Generic tornado plotter

---

CHANGELOG.md
webviz_subsurface/_components/tornado/_tornado_table.py
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/__init__.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/export_data_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/layout_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/figures/px_figure.py
webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
webviz_subsurface/plugins/_volumetric_analysis/views/clientside_stores.py
webviz_subsurface/plugins/_volumetric_analysis/views/distribution_main_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/filter_view.py
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
webviz_subsurface/plugins/_volumetric_analysis/views/tornado_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/tornado_selections_view.py
webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py

Various improvement to the `VolumetricAnalysis `plugin.
---

Tornadoplots, and further improvements to `VolumetricAnalysis`

---

CHANGELOG.md
setup.py
tests/integration_tests/test_ert_jobs.py
webviz_subsurface/ert_jobs/config_jobs/SMRY2ARROW
webviz_subsurface/ert_jobs/jobs.py
webviz_subsurface/ert_jobs/smry2arrow.py

This PR adds an ERT forward model that can converts `.UNSMRY` files to Apache Arrow IPC file format.
The Arrow IPC file format is a columnar data format optimized for table-like datasets, see https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format
This file format is also known as `Feather` version 2, see https://arrow.apache.org/docs/python/feather.html
The ERT job imports data from an `.UNSMRY` file and writes output to an `.arrow` file in the above format.
The following data types are used in the exported data
- `DATE` column is stored as an Arrow timetamp with millisecond resolution `timestamp[ms]`
- All numeric columns will be stored as 32 bit floats
- Summary meta data will be attached to each field/column in the exported table's schema under the
'smry_meta' key
Currently …

Added ERT forward model to convert from .UNSMRY to Arrow file format

---

webviz_subsurface/_components/tornado/_tornado_bar_chart.py
webviz_subsurface/_components/tornado/tornado_widget.py

PR to fix bug when no sensitivities have impact on a response and the "Remove sensitivities with no impact" is active.
This resulted in error before. Now an empty plot with only the refrence line is drawn.
---

Bugfix TornadoPlot when no sensitivities have impact

---

setup.py

clientside_stores in _volumetric_analysis plugin utilize dcc.Download. Component requires dash-core-components 1.16.0, which is included in dash 1.20.0

Update required dash version to 1.20.0 due to dcc 1.16.0 dependency

---

webviz_subsurface/_components/tornado/_tornado_data.py

After `pandas==1.3` that was released three days ago, CI on Python 3.7-3.8 has started to consistently fail (Python 3.6 succeeds due to recent version of Pandas not being installed on that Python version).
According to https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.all.html it looks like `all()` returns a boolean by itself, and the pattern `df["somecolumn"].all() == x` does not seem to be documented on that page. But apparently it worked for `pandas < 1.3`? :thinking: 
I checked for other occurrences by doing `grep -rnw './webviz-subsurface' -e '.all()'` giving only matches for the file `_tornado_data.py`.

Use `pd.all()` in documented way

---

CHANGELOG.md
webviz_subsurface/plugins/_relative_permeability.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py

Introduces `uirevision` to keep zoom state in more plugins where it felt natural. 
There is a risk that some users are not familiar with plotly zoom and how to revert it to initial state, but it is fairly easy (either double click in plot or use the plot toolbar)
Replaces the test in #701 
---

Preserve uirevision in timeseries and relperm plugins

---

webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
webviz_subsurface/plugins/_parameter_analysis/views/main_view.py
webviz_subsurface/plugins/_parameter_analysis/views/parameter_qc_view.py
webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py

This PR addresses issue #722, and implements the  `ParameterFilter` component to the "Parameters impact on simulation profiles" tab of the `ParameterAnalysis` plugin.
- Added checkbox to be able to display/hide the ParameterFilter component 
- Added realization filter to filter data used for the figures and correlations.
- Added return of empty figures if there is no data left after filtering.
Also included in the PR:
- minor layout fixes to adjust some margins etc. after the wcc layout components was implemented
- set tab "Parameters impact on simulation profiles" as selected tab, if smry data is available, to make it more visible for users looking through the Reek examples.
---

Added parameter filter to ParameterAnalysis

---

webviz_subsurface/_components/parameter_filter.py

PR includes:
- smaller font on header
- prevent having to scroll down to find "apply" and "reset" buttons by inheriting size of parent div instead of setting fixed height 
- Position and color adjustment of "apply" and "reset" button 
Before          |  After
:-------------------------:|:-------------------------:

Layout updates to `ParameterFilter`

---

.pylintrc
webviz_subsurface/_utils/simulation_timeseries.py
webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py

Adding exception for encoding in pylint. Investigate further whether `utf-8` should be enforced (separate issue #740 )
---

Updates for `pylint=2.10.2`

---

CHANGELOG.md
webviz_subsurface/_assets/css/inplace_volumes.css
webviz_subsurface/_components/tornado/_tornado_bar_chart.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/layout_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/views/distribution_main_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py

This PR adds a "Tables" tab in `VolumetricAnalysis` for easy user access to custom table generation.  
Today the user has to turn off the "sync table with plot" option on the tables belonging to the plots in order to make custom tables. With this PR these tables are no longer customizable, but are kept as statistics tables similar to the old `InplaceVolumetrics` plugin. With this change a lot of logic can be removed from the code.
This PR also includes removal of unnecessary initial callback check in each page update callback.

Added Tables tab in `VolumetricAnalysis`

---

CHANGELOG.md
setup.py
webviz_subsurface/_models/well_set_model.py
webviz_subsurface/plugins/__init__.py
webviz_subsurface/plugins/_well_log_viewer/__init__.py
webviz_subsurface/plugins/_well_log_viewer/_validate_log_templates.py
webviz_subsurface/plugins/_well_log_viewer/controllers/__init__.py
webviz_subsurface/plugins/_well_log_viewer/controllers/_well_controller.py
webviz_subsurface/plugins/_well_log_viewer/well_log_viewer.py

Well log viewer

---

webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/views/clientside_stores.py

Bugfix `VolumetricAnalysis` to trigger callbacks on a page-refresh. 
- Memory storage using dcc.Store has been added to keep track of which pages has been initially loaded after a page refresh. This info is in turn used to trigger the necessary callbacks for displaying data.
- Also removed two unused dcc.Store variables

Bugfix in `VolumetricAnalysis` to trigger callbacks on page refresh

---

CHANGELOG.md
webviz_subsurface/_providers/ensemble_table_provider_factory.py

We should agree on how far out in the factory code the filter option should be exposed. 
Right now, I added to only the innermost function wrapping the call to `ScratchEnsemble` and then defaulting the filter to `OK`, but could maybe be use cases where the filter is not wanted, and where the option of no filter (by setting `filter_file = None` ) is useful?
---

Filter on OK in `ensemble_table_provider_factory`

---

CHANGELOG.md
webviz_subsurface/plugins/_property_statistics/controllers/property_delta_controller.py
webviz_subsurface/plugins/_property_statistics/controllers/property_qc_controller.py
webviz_subsurface/plugins/_property_statistics/controllers/property_response_controller.py
webviz_subsurface/plugins/_property_statistics/models/property_statistics_model.py
webviz_subsurface/plugins/_property_statistics/property_statistics.py
webviz_subsurface/plugins/_property_statistics/utils/surface.py
webviz_subsurface/plugins/_property_statistics/views/main_view.py
webviz_subsurface/plugins/_property_statistics/views/property_delta_view.py
webviz_subsurface/plugins/_property_statistics/views/property_qc_view.py
webviz_subsurface/plugins/_property_statistics/views/property_response_view.py
webviz_subsurface/plugins/_property_statistics/views/selector_view.py

Handle missing surfaces in PropertyStatistics and support changes in input format

---

CHANGELOG.md
webviz_subsurface/_models/surface_set_model.py

Store xtgeo.RegularSurface as bytestream instead of serializing to json for increased performance.
Note that older portable applications will not work with this change.

Store `xtgeo.RegularSurface` as bytestream

---

CHANGELOG.md
setup.py
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/views/distribution_main_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py
webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py

Up until now the VolumetricAnalysis plugin has only supported static input. This PR fixes that issue.
The PR includes:
- Automatic detection of what fluid_type the different volumetric files are (static vs dynamic)
- if only dynamic files are given as input, no processing is performed in the InplaceVolumesModel (e.g. removal of column fluid suffixes and computation of properties from the volumetric data)
- Validation of the static volume files as they must fit a strict format to be fit for the input processing done in the InplaceVolumesModel.
- Utilization of the FipMapper from fmu.tools for creating sets of FIPNUM's and REGION∕ZONE's that are comparable
in volumes, and combining volumes per set. To trigger this behaviour a fipfile with FIPNUM to REGION∕ZONE mapping information needs to …

Support eclipse volumes in `VolumetricAnalysis`

---

CHANGELOG.md
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/views/filter_view.py
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py

PR which adds functionality of easy switching between `fipnum` or `region/zone` as filter if all three selectors are present in `VolumetricAnalysis` (this occurs in cases where each fipnum value belongs to an unique region and zone). 
- When the user switches between a fipnum or a region/zone filter, the current filter selection is used to set the new selection e.g. when a fipnum selection is made and the user switches to a region/zone filter the zones and regions containing those fipnums are selected.
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/61694854/134050837-2ad268e4-b70e-4867-bebf-2b834ff39696.png)  | ![image](https://user-images.githubusercontent.com/61694854/134051342-43a9f751-f1dd-4657-8a75-274ea13523d4.png) |
---

Added region/zone vs fipnum filter switch in `VolumetricAnalysis`

---

CHANGELOG.md
webviz_subsurface/_figures/px_figure.py
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/__init__.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/utils/table_and_figure_utils.py
webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py

PR which adds content to the `Source comparison` and `Ensemble comparison` tabs in `VolumetricAnalysis`.
These tabs are focused on computing differences between sources/ensembles, and is a tool for quick detection of where and why volumetric changes occur.
Both tabs have the same layout and functionality:
- Highlight data based on criteria to quickly detect where volumes changes occur
- Flexible selection of level of investigation
- Plots for visual inspection of correlation etc.
- Tables for looking at the differences for the selected response 
- Tables for looking at differences for multiple responses together to understand why volumes are changing
The` Source comparison` is useful for comparing volumes between:
- geogrid and upscaled grid from RMS. 
- static volumes and dynamic volumes …

Added source and ensemble comparison to `VolumetricAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py

Bugfix in `VolumetricAnalysis` do not split data per realization before taking mean for property columns when `Mean table` is selected. Property columns should be computed on the grouped volumetric data.
Bug was introduced in  #724

Bugfix property calculation in mean table `VolumetricAnalysis`

---

webviz_subsurface/plugins/_reservoir_simulation_timeseries.py

Fixes a bug in the still unreleased #709 where the logic to allow missing predefined_expressions broke after rewriting the shared_settings verification steps.

Allow no `predefined_expressions` in `ReservoirSimulationTimeseries`

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py

User request.
Handle SENSNAME in same manner as SOURCE/ENSEMBLE by not allowing more than one SENSNAME to be selected as filter if the user has not grouped on this column. This is to avoid misleading statistical numbers.
The standard name for the SENSNAME with "base case" simulations is "rms_seed", this is used as default if present when SENSNAME has not been grouped on.

Prevent mixing volumes from different sensitivities in `VolumetricAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/controllers/__init__.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/fipfile_qc_controller.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/views/fipfile_qc_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py

PR which adds a Fipfile QC tab to VolumetricAnalysis.
This tab will only appear if users inputs a fipfile.
When comparing static and dynamic volumes the fipfile is used to guide which fipnums and regions/zones to sum over to get comparables volumes. If the user makes this file manually errors can occur. This tab presents a way of QC'ing the mapping between fipnum vs zone/region and to see what data are grouped together by the fipmapper (SETs).
- this is done in both a visual manner using heatmaps and by table form 
---

Added fipfile QC tab to VolumetricAnalysis

---

webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py

For ensembles it doesn't make sense to compare on realization level like it does for sources. 
This PR removes the realization vs diff plot from the layout and removes the option of grouping on realization level for the `Ensemble comparison` tab in `VolumetricAnalysis`.
Edit to the not released #777
| Source comparison layout | Ensemble comparison layout |
| -----------------------------|---------------------------------|
|![image](https://user-images.githubusercontent.com/61694854/134563503-cbab6229-2ac4-4ee4-9336-7a0a168be381.png) | ![image](https://user-images.githubusercontent.com/61694854/134563541-afce17c3-25d3-42e4-8b1d-63a0c76a9bea.png) |

Layout change Ensemble comparison tab `VolumetricAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_surface_viewer_fmu.py

When switching between attributes with different geometry the map bounds are not updated. There seems to be an issue using `updateMode="update"`. 
Switching to `updateMode="replace"` fixes the issue.

Ensure map bounds are updated when switching attribute in `SurfaceViewerFMU`

---

CHANGELOG.md
webviz_subsurface/_models/parameter_model.py

Bugfix in the sensitivity run detection logic in `ParametersModel`. 
Desired behavior, if only ensembles with single montecarlo sensitivities the run should not be flagged as a sensitivity run.

Bugfix sensitivity run detection `ParametersModel` 

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py

PR with small bugfixes for `VolumetricAnalysis`:
Comparison pages:
1. Handle None in the Input components by setting a default value of 0
2. Fix issue to avoid data from the different FLUID_ZONEs stacking upon eachother in the barfigure
3. Use "Total" as label in the barfigure if no "level of investigation" has been selected
Other:
1. Removed "BO" and "BG" as option in tornado as they will cause error if multiple FLUID_ZONEs exists
2. Print out "valid static columns" for the user if the volume type most likely is static but contains either custom columns or not standard column names. 
3. Remove TOTAL columns if both static and dynamic volumes have been given as input to avoid misleading comparison (they often represent different things)
4. Remove rows with total volumes from selectors if …

Bugfixes `VolumetricAnalysis`

---

webviz_subsurface/plugins/_group_tree/group_tree.py

Fixed #806 by adding time_index="monthly" to the loading of summary data. Ommiting that led to loading raw eclipse dates which were not even the same over the realizations.

Runtime improvement in GroupTree plugin

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/fipfile_qc_controller.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/views/tornado_view.py

PR with bugfixes to the `VolumetricAnalysis` plugin:
- Handle empty dataframes after filtering in the `comparison` pages 
- Handle empty dataframes and missing tornado reference after filtering in the `tornadoplots` page 
- Fix error in the "update" logic of pages – set the initial_load state to False after a user selection is made
- Ensure the filter for the selected subplot column is set to multi in the `tornadoplots` page

Bugfixes to `VolumetricAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_seismic_misfit.py

Seismic misfit improvements

---

setup.py

Removed `ert` from test dependencies since it is no longer needed and causes test run to fail.

Removed `ert` from test dependencies

---

tests/unit_tests/model_tests/test_ensemble_model.py
tests/unit_tests/model_tests/test_ensemble_set_model.py

Version 2.13.1 of `ecl` fixes some precision issues for calculation of timestamps, see https://github.com/equinor/ecl/pull/837
This PR updates the expected target values for our tests to match the new results from `ecl`

Updated target values in tests due to fixes in ecl 2.13.1

---

CHANGELOG.md
webviz_subsurface/plugins/_parameter_response_correlation.py

PR with improvements to the `ParameterResponseCorrelation` plugin:
- Parsing of the parameter dataframe with ParameterModel to remove prefixes from gen_kw, and drop constant parameters 
- Added option of setting the maximum number of parameters shown in the correlation bar
- Added trendline to scatterplot
- Set xaxis range for correlation barchart from data instead of using -1 and 1
After:
Before:
---

Fixes to `ParameterResponseCorrelation`

---

CHANGELOG.md
webviz_subsurface/_models/parameter_model.py

PR to support a mix of sensitivity ensembles and gen_kw ensembles in `ParametersModel`. 
A dice is added as SENSNAME to gen_kw ensembles for easy distinction from sensitivity ensembles:

Allow mixing sensitivity and gen_kw ensembles in `ParametersModel`

---

CHANGELOG.md
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py

This PR adds the functionality of comparing sensitivities across or within ensembles in the "Ensemble Comparison" tab in `VolumetricAnalysis`
- If single sensitivity ensemble as input the tab changes name to "Sensitivity comparison"
---

Added sensitivity comparison to `VolumetricAnalysis`

---

webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py

Was too quick with the bugfix on friday.. 🤔 
..need to ensure "SENSNAME_CASE" is not present as index, otherwise not possible to compare sensitivities across ensembles

Second bugfix on sensitivity comparison in VolumetricAnalysis

---

webviz_subsurface/plugins/_group_tree/group_tree_data.py

This bug relates to node type classification of BRANPROP group leaf nodes. Group leaf nodes are classified by using summary data, but BRANPROP nodes does not have injection summary vectors by definition.  Therefore the `create_leafnodetype_maps` function was crashing.
This bug is fixed by setting suminj = 0 for BRANPROP group `nodes.`

 `GroupTree` plugin: bugfix related to BRANPROP group leaf nodes

---

CHANGELOG.md
tests/unit_tests/provider_tests/test_ensemble_summary_provider.py
webviz_subsurface/_providers/ensemble_summary_provider/_arrow_unsmry_import.py
webviz_subsurface/_providers/ensemble_summary_provider/dev_compare_fmu_to_lazy_provider.py
webviz_subsurface/_providers/ensemble_summary_provider/dev_provider_perf_testing.py
webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider_factory.py

Added new `rel_file_pattern` argument to `EnsembleSummaryProviderFactory.create_from_arow_unsmry_lazy()` and `EnsembleSummaryProviderFactory.create_from_arrow_unsmry_presampled()` methods.
---

Added `rel_file_pattern` argument to EnsembleSummaryProviderFactory methods

---

CHANGELOG.md
webviz_subsurface/plugins/_structural_uncertainty/figures/intersection.py
webviz_subsurface/plugins/_structural_uncertainty/views/intersection_data.py

Change label and add hoverinfo for uncertainty envelope in StructuralUncertainty

---

webviz_subsurface/plugins/_simulation_time_series/_callbacks.py
webviz_subsurface/plugins/_simulation_time_series/utils/from_timeseries_cumulatives.py

The old `ReservoirSimulationTimeSeries` has some logic to modify the `DATE` column when downloading the special vectors that we calculate from cumulatives over a certain interval in time (those starting with AVG_ and INTVL_). The logic was introduced to reduce risk of misunderstandings from users related to whether the date was e.g. at the beginning of the interval, at the end, or the middle. Instead, the `DATE` axis was reduced down to what describes the interval best. A yearly interval would leave only `YYYY`, a monthly would give `YYYY-MM` and daily would give `YYYY-MM-DD`.
This PR implements the same logic for the new `SimulationTimeSeries` plugin, though now using the `Frequency` dataclass + extended to support weeks and quarters.

Format dates in download for resampled date in SimulationTimeSeries

---

CHANGELOG.md
webviz_subsurface/_assets/css/inplace_volumes.css
webviz_subsurface/_figures/px_figure.py
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/fipfile_qc_controller.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/layout_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/utils/table_and_figure_utils.py
webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/distribution_main_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/fipfile_qc_layout.py
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
webviz_subsurface/plugins/_volumetric_analysis/views/tornado_view.py

Several improvements to VolumetricAnalysis, some based on of user-feedback.
**Main changes `Inplace distributions` tab**
- Merged functionality in pages `1 plot/1 table` and `Custom plotting`, in order to make it less confusing for the users what page to use, and also simplify the code logic. The only real difference between the two pages was that the user could make subplots in the `Custom plotting`. This is still available, and an option to hide the table below is added to make more space for the subplots. 
- Added useful "colorby" feature to the barplots in `Plots per zone/region` page. If colorby is selected the piechart is hidden.
- Change to returning entire layout for the pages, instead of individual figures --> if a selection/filter changes all plots needs to be updated anyway. …

General improvements to VolumetricAnalysis

---

webviz_subsurface/plugins/_simulation_time_series/_callbacks.py

Adds the statistics after the individual realizations rather than before, meaning that the statistics will be placed on top (though only for the given vector/ensemble. Additional vectors/ensembles will still be placed on top). Makes it easier to see statistics when plotting both (note difference in the area to the lower left with very high density of realizations covering all of the statistics).
Example:
Old behavior:
New behavior:

`SimulationTimeSeries`: Add statistics after realizations

---

webviz_subsurface/plugins/_rft_plotter/_callbacks/callbacks.py
webviz_subsurface/plugins/_rft_plotter/_callbacks/parameter_response_callbacks.py
webviz_subsurface/plugins/_rft_plotter/_layout.py

This PR fixes the problem of not being able to update selections by clicking in the bar chart when the chart is in param_vs_sim mode. The trick is to avoid callbacks triggering each other in an infinite loop, but that is solved by updating the whole dropdown objects (for date and zone) instead of only the value.
Also fixes a bug in the callback that was updating the formations well by clicking in the map.

RftPlotter: update param response selections by clicking in bar chart

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py

Fix: Skip emodel in `webvizstore` in `VolumetricAnalysis for aggregated input

---

CHANGELOG.md
tests/integration_tests/test_parameter_filter.py
webviz_subsurface/_components/parameter_filter.py
webviz_subsurface/_models/parameter_model.py
webviz_subsurface/plugins/_line_plotter_fmu/line_plotter_fmu.py
webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_qc_controller.py
webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
webviz_subsurface/plugins/_parameter_analysis/views/main_view.py
webviz_subsurface/plugins/_parameter_analysis/views/parameter_qc_view.py
webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py

PR with bugfixes and improvements to the `ParameterFilter` component and to the `ParameterAnalysis` plugin
**Bugfixes:**
- Handle NaN values in parameter dataframe that enters the `ParameterFilter`. NaN values in the Select component caused issues when trying to render the layout. 
**Added functionality:**
- Option to choose which ensemble to filter on 
- Option to use range from selected ensemble or from all ensembles
- Active Filter indicator where the user can see which parameters are active and their ranges
- Information regarding which realizations are removed with the current filter   
- Apply button changes color when selected filters is not in sync with stored filters
**Bugfixes:**
- If only one realization left after filtering the correlation would fail in the `ParameterAnalysis` …

Bugfixes and improvements to `ParameterFilter` and `ParameterAnalysis`

---

webviz_subsurface/_components/parameter_filter.py

Bugfix on non-released feature.
Ensure numbers are always float before using the `is_integer()` check since this method does not work on numpy floats or integers in python versions<3.8.

Bugfix in `ParameterFilter`

---

CHANGELOG.md
tests/unit_tests/plugin_tests/test_simulation_time_series/test_utils/test_create_vector_traces_utils.py
webviz_subsurface/plugins/_simulation_time_series/_property_serialization/vector_subplot_builder.py
webviz_subsurface/plugins/_simulation_time_series/utils/create_vector_traces_utils.py

Fix incorrect hover info for observation trace in `SimulationTimeSeries`-plugin when grouped by Time Series.
Default name and legend group fixing issue with trace name in hover info.
Resolves issue: https://github.com/equinor/webviz-subsurface/issues/931
----
- Default legend group and name "Observation".
- Updated unit test

Fix hover info for observation trace new SimulationTimeSeries plugin

---

webviz_subsurface/plugins/_rft_plotter/_business_logic.py

Fixes a bug in `RftPlotter` that caused the plugin to crash when it was run with an aggregated `csv `file. The bug came from updates in the `ParametersModel `class. It is fixed by passing a dummy dataframe to `ParametersModel`. The dummy dataframe is made so that the ensembles will be identified as sensitivity runs. Then the parameters response tab will not be added.

Adjustments in  `RftPlotter` due to changes in `ParametersModel`

---

.github/workflows/subsurface.yml

As a temporary workaround for upstream https://github.com/statsmodels/statsmodels/issues/8110 we skip Docker test build on Python 3.7.

Temp. CI/CD workaround `statsmodels`

---

CHANGELOG.md
tests/unit_tests/plugin_tests/test_well_completions.py
webviz_subsurface/_datainput/well_completions.py
webviz_subsurface/plugins/_well_completions/_business_logic.py

This PR extends the functionality in the `WellCompletion` plugin so that it handles zone->layer mappings that are potentially different across realizations (as is the case in the Drogon sample data).
---

`WellCompletion` handling different zone → layer mappings over realizations

---

CHANGELOG.md
webviz_subsurface/plugins/_simulation_time_series/_plugin.py

Add list of vectors as user input option for `SimulationTimeSeries`-plugin
---
- Add list of vectors as user input for initially selected vectors.
- Deprecate usage of {vector1, vector2, vector3}
- Add ValueError for missing vectors
---
* https://github.com/equinor/webviz-subsurface/issues/677

Add list of vectors as user input for `SimulationTimeSeries`

---

webviz_subsurface/plugins/_simulation_time_series/_callbacks.py
webviz_subsurface/plugins/_simulation_time_series/_layout.py

Replace the `Modal`-component from `Dash Bootstrap Components` with new draggable `Dialog`-component in `wcc`.
---
* https://github.com/equinor/webviz-subsurface/issues/959

Replace VectorCalculator modal with draggable dialog in SimulationTimeSeries

---

CHANGELOG.md
webviz_subsurface/plugins/_rft_plotter/_business_logic.py
webviz_subsurface/plugins/_rft_plotter/_callbacks/callbacks.py
webviz_subsurface/plugins/_rft_plotter/_callbacks/parameter_response_callbacks.py
webviz_subsurface/plugins/_rft_plotter/_figures/_errorplot_figure.py
webviz_subsurface/plugins/_rft_plotter/_figures/_formation_figure.py
webviz_subsurface/plugins/_rft_plotter/_figures/_map_figure.py
webviz_subsurface/plugins/_rft_plotter/_layout.py

Various improvements to the `RftPlotter`, including zone filter in map plot and parameter filter in the parameter response tab.
---

Zone filter and parameter filter in `RftPlotter`

---

CHANGELOG.md
webviz_subsurface/plugins/_property_statistics/views/property_response_view.py
webviz_subsurface/plugins/_surface_with_grid_cross_section.py
webviz_subsurface/plugins/_surface_with_seismic_cross_section.py

In Dash > 2.10 the `RangeSlider` component automatically calculates `marks` from `min` and `max`.
If `min` and `max` is not provided this calculation fails.
Marks are not needed for our use, so we can set `marks=None` to disable this behaviour.
---

Disable rangeslider marks in cross-section plugins

---

CHANGELOG.md
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py

Bugfixes in `VolumetricAnalysis`:
-  Selecting only BO and/or BG in the table introduced a bug in pandas saying "no numeric types to aggregate". This is avoided by setting these to nan instead of "NA" when the data was not grouped on "FLUID_ZONE"  
- If volumefiles from one ensemble contained PORE and volumefiles from another enemble contained PORV, the PORV renaming led to two columns with PORV in the merged dataset and an error occured.
---

Two bugfixes in `VolumetricAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_well_log_viewer/utils/xtgeo_well_log_to_json.py

Fix to support Well log Viewer in version 0.4.10. Data format changed from list of json object to a single object.
Also removed some unused metadata that had the wrong format.
This PR closes #984.

Update `WellLogViewer` data format to latest version

---

webviz_subsurface/plugins/_simulation_time_series/_layout.py

Place in div with fixed height for new VectorCalculator refactoring in https://github.com/equinor/webviz-subsurface-components/pull/860.
`wcc.Dialog` adjusts to content and `VectorCalculator` is refactored to adjust to parent, thus height is controlled by div width

Place `VectorCalculator` in `Div` with fixed height

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py

An old statement (not needed anymore) caused the "Tornadoplots" tab in `VolumetricAnalysis` to not appear if both static and dynamic volume sources were mixed.

Bugfix `VolumetricAnalysis` - tornados hidden if both dynamic and static sources

---

webviz_subsurface/plugins/_parameter_analysis/data_loaders/__init__.py
webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
webviz_subsurface/plugins/_property_statistics/data_loaders/__init__.py
webviz_subsurface/plugins/_property_statistics/models/simulation_timeseries_model.py
webviz_subsurface/plugins/_property_statistics/property_statistics.py

The non released #988 introduces support for .arrow files in `ParameterAnalysis` and `PropertyStatistic`, which would cause older portable App's to fail if they have one of these plugins included.
This PR is a fix to introduce backwards compatibility to allow these portables to still function.
- arrow formats as input to `ParameterAnalysis` and `PropertyStatistic` are required for all new builds of webviz, otherwise an error is raised (with explanatory text)
- however if the run_mode is **portable** it first looks for the arrow files, but if not found the old methods of loading summary data and csv's are tried.
Benefits:
- portables built before the requirement of .arrow files will still work
- all new portables will have arrow files, which will lead to an easier removal of the old …

Add backwards compatibility for older portables using `ParameterAnalysis` and `PropertyStatistic`

---

webviz_subsurface/plugins/_parameter_response_correlation.py

---
Tbh; Not sure why the parenthesis is needed for the filter selectors, but for some reason it makes a difference...
Have skipped changelog, as I am not really sure why this in fact is a "fix". Seems to work though...

Fix issues with just one parameter and for aggregated data in `ParameterResponseCorrelation`

---

CHANGELOG.md
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_bhp_qc.py
webviz_subsurface/plugins/_parameter_response_correlation.py
webviz_subsurface/plugins/_swatinit_qc/_business_logic.py
webviz_subsurface/plugins/_swatinit_qc/_figures.py
webviz_subsurface/plugins/_volumetric_analysis/volume_validator_and_combinator.py

PR with bugfixes:
1. `ParameterResponseCorrelation` and `BhpQc`: add step=1 to slider to prevent bug due to float numbers
3. `SwatinitQC`: don't show contacts if the contacts are shallower than the dataset (dummy contacts)
4. `VolumericAnalysis`: only include numeric columns as volumetric responses
7. `VolumericAnalysis`: remove rows with Totals" before summing volumes over disjoint sets 
6. `VolumericAnalysis`: prevent rows beeing removed if the License is called "Totals" ("Totals" should only be removed from `Zone/Region/Facies`)

Various bugfixes

---

CHANGELOG.md
tests/unit_tests/provider_tests/test_ensemble_summary_provider_impl_arrow_lazy.py
webviz_subsurface/_providers/ensemble_summary_provider/_provider_impl_arrow_lazy.py
webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider_factory.py

Improved error reporting when loading `.arrow` files that contain dates that are not strictly monotonically increasing.
Now reports both the failing realization number and the two first offending timestamps. 
Also chains in an additional exception to indicate the failing ensemble.
This PR is related to #979. It does not mitigate the issue but provides additional on why and where the problem occurs.

Improved error reporting for `.arrow` files where dates are not monotonically increasing.

---

CHANGELOG.md
webviz_subsurface/plugins/_seismic_misfit.py

Some improvements to the `SeismicMisfit` plugin
---

`SeismicMisfit` - support new polygon header standard

---

CHANGELOG.md
webviz_subsurface/_providers/__init__.py
webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider.py
webviz_subsurface/_providers/ensemble_summary_provider/utils.py
webviz_subsurface/plugins/_parameter_response_correlation.py

This PR implements the new summary data provider i `ParameterResponseCorrelation`. 
I also needed to make a general function that matches column_keys with * as wildcard. I have put it in EnsembleSummaryProvider, but we can discuss where it should be.

New data provider in `ParameterResponseCorrelation`

---

CHANGELOG.md
webviz_subsurface/plugins/_simulation_time_series/_layout.py
webviz_subsurface/plugins/_simulation_time_series/_property_serialization/vector_subplot_builder.py

Increased maximum number of selected vectors in `SimulationTimeSeries` to 100.
Also modified the vertical spacing between subplots to avoid error when requesting > 21 subplots (both when plotting per time series or per ensemble). Only relevant to avoid errors, as that many subplots will anyways be useless considering the height of each plot. 
---
_- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR._ **No tests added**

Increased maximum number of selected vectors in `SimulationTimeSeries`

---

CHANGELOG.md
webviz_subsurface/plugins/_prod_misfit/_plugin.py

It was not taken into account, i.e. it had no effect, due to badly placed continue
inside nested loop.

`ProdMisfit`- fixed bug related to use of excl_name_contains.

---

.github/workflows/subsurface.yml

The newest `dash` version does no longer come with a `_NoUpdate` class which is used by some of the plugins in `webviz_subsurface`. In order to give the plugin authors time to fix this issue/find a different solution, the `dash` version was pinned to `<2.6.0` in the GitHub workflow (in order to avoid failing checks).
---

Pinned `dash` to `<2.6.0` in order to keep `_NoUpdate` class available.

---

.github/workflows/subsurface.yml
webviz_subsurface/plugins/_property_statistics/controllers/property_response_controller.py
webviz_subsurface/plugins/_structural_uncertainty/controllers/map_controller.py

It looks like the private class `NoUpdate` was moved in https://github.com/plotly/dash/commit/43e42eaecbd912c5391db5acd81566a35786a26a.
The class is only used in type checking on our side, so we have two options:
* Coninue use the dash private class in the type checking.
* Loosen up the type checking on our side.
After discussion, we go for the first solution, and hope dash itself gets type hinted in the near future (such that also `NoUpdate` becomes a public entity).

Support `dash>=2.6`

---

CHANGELOG.md
webviz_subsurface/plugins/_parameter_response_correlation.py

Fixed a bug in `ParameterResponseCorrelation` that caused the plugin to fail if `response_filters` was not given as input parameter. Now the filters layout will always be added with at least the parameter filter.
---

Bugfix in `ParameterResponseCorrelation`

---

CHANGELOG.md
webviz_subsurface/plugins/_map_viewer_fmu/layout.py

Remove `zoom` and `bounds` prop as these are now calculated automatically.

Update MapViewerFMU to new changes in DeckGLMap component

---

webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_settings/_time_series.py

`open` is not required prop for wcc.Dialog, thus initial value was undefined, and the data type was undefined - i.e `None`. Resolved by defining initial state False, thus `open.propType = boolean` in `React`-component and python type is `bool`.

Fix `callback_typecheck` error for `wcc.Dialog` prop in `SimulationTimeSeries`

---

webviz_subsurface/_components/parameter_filter.py
webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_settings/_parameter_filter.py

The header in the Parameter filter is not needed when it is used in a WLF settings group, because it has it's own name. This makes the header optional. But the default behavior is as before.
---

Option to remove header from parameter filter

---

.github/workflows/subsurface.yml
setup.py
tests/unit_tests/provider_tests/test_ensemble_table_provider.py
webviz_subsurface/_providers/__init__.py
webviz_subsurface/_providers/ensemble_table_provider/__init__.py
webviz_subsurface/_providers/ensemble_table_provider/_field_metadata.py
webviz_subsurface/_providers/ensemble_table_provider/ensemble_table_provider.py
webviz_subsurface/_providers/ensemble_table_provider/ensemble_table_provider_impl_arrow.py

Implements the possibility to extract column metadata from the `EnsembleTableProvider`. It is needed in the `WellCompletion` plugin to get the KH unit.
Only unit is so far implemented, but it is easily extended to other column metadata
---

Metadata functionality in `EnsembleTableProvider`

---

.github/workflows/subsurface.yml
webviz_subsurface/_models/gruptree_model.py

The terminal node filtering of the gruptree dataframe was taking a lot of time if there was many timesteps and realizations. This fixes it by dropping duplicate child nodes and not filtering if the terminal_node is `FIELD`.
---

`GroupTree`: Improved terminal_node filtering

---

.github/workflows/subsurface.yml
mypy.ini

`mypy` with version `>= 0.990` has changed its default to `no_implicit_optional=True`. This implies error for all missing `Optional` or `Union[..., None]` where default value is set to `None`.
Temporary solution is to set `implicit_optional=True` in `mypy.ini` as plugin `__init__`-functions cannot handle usage of `Optional` when JSON Schema is generated using typehints runtime.
Closes: #1154

Set `implicit_optional=True` for `mypy`

---

webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_settings/_ensembles.py

Place the `Delta Ensembles` in a `wcc.Selectors` component rather than a `wcc.LabeledContainer` to obtain open/close functionality. 
Requested by users: `wcc.Selectors` rather than `Delta Ensembles` as a separate `WebvizSettingsGroup` in the settings drawer for `WLF` - to keep the `Delta Ensemble` functionality grouped with the `Ensembles`.
Closes: #1151

Replace wcc.LabeledContainer with wcc.Selectors for `Delta Ensembles` in `SimulationTimeSeries`

---

.github/workflows/subsurface.yml
CHANGELOG.md
tests/unit_tests/provider_tests/test_ensemble_summary_provider.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
webviz_subsurface/_datainput/fmu_input.py
webviz_subsurface/_datainput/history_match.py
webviz_subsurface/_datainput/well_completions.py
webviz_subsurface/_models/ensemble_model.py
webviz_subsurface/_providers/ensemble_fault_polygons_provider/_fault_polygons_discovery.py
webviz_subsurface/_providers/ensemble_summary_provider/_csv_import.py
webviz_subsurface/_providers/ensemble_surface_provider/_surface_discovery.py
webviz_subsurface/_providers/ensemble_table_provider/ensemble_table_provider_factory.py

Make it possible to `import webviz_subsurface` without `opm` and `ecl2df`. Include test install and import on `windows`

---

.github/workflows/subsurface.yml
setup.py
webviz_subsurface/plugins/_grid_viewer_fmu/_plugin.py

`webviz_vtk` is not yet a `PyPi` package and can therefore not be part of the regular release (not sure if it will be a problem to have it in `extras_require` too? But guess the easiest way to find out is to test.

`vtk` modules are added to `extras_require`

---

.github/workflows/subsurface.yml
setup.py
webviz_subsurface/plugins/_grid_viewer_fmu/_plugin.py

Due to `webviz_vtk` not being a `PyPi` package. Follow up after attempt of having it as an `extras_require` in #1166 which turned out to not be enough

Remove `vtk` from dependencies

---

CHANGELOG.md
webviz_subsurface/plugins/_well_analysis/_utils/_ensemble_well_analysis_data.py

Fixes a bug in `WellAnalysis`.
Since the dates in the `only production after date` dropdown is the union of dates in all ensembles, it can happen that the selected date is > all dates in a selected ensemble. In that case the date is now set equal to the max date for the given ensemble.
---

Bugfix in `WellAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_co2_leakage/_plugin.py
webviz_subsurface/plugins/_co2_leakage/_utilities/callbacks.py
webviz_subsurface/plugins/_co2_leakage/views/mainview/mainview.py

Remove `deck.gl` bounds and use only relevant ensembles in CO₂ plugin

---

CHANGELOG.md
webviz_subsurface/plugins/_parameter_response_correlation.py

When we switch from csv file `response_file` to arrow file `rel_file_pattern`, we get an error which basically requires us to specify the column_keys instead of set it to default `None` 
Specifying all the column_keys in advance could be tedious and in-practical in some cases. So, it is desired to keep the same behavior (load all columns) as when we are using csv file as input.
---

ParameterResponseCorrelation empty column_keys

---

.github/workflows/subsurface.yml
webviz_subsurface/_providers/ensemble_surface_provider/surface_array_server.py
webviz_subsurface/_providers/ensemble_surface_provider/surface_image_server.py
webviz_subsurface/plugins/_co2_leakage/_plugin.py
webviz_subsurface/plugins/_co2_leakage/_utilities/callbacks.py
webviz_subsurface/plugins/_co2_leakage/views/mainview/mainview.py
webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/_view_3d.py
webviz_subsurface/plugins/_grid_viewer_fmu/views/view_3d/view_elements/_vtk_view_3d_element.py
webviz_subsurface/plugins/_map_viewer_fmu/callbacks.py
webviz_subsurface/plugins/_map_viewer_fmu/layout.py

Fix `DeckGLMap` renamed to `DashSubsurfaceViewer`.
Use the `children` prop to display view annotations for label and color legends.

Use view annotations in mapviewerfmu

---

CHANGELOG.md
webviz_subsurface/plugins/_swatinit_qc/_business_logic.py
webviz_subsurface/plugins/_swatinit_qc/_figures.py

By default, datatio writes X, Y, Z, ID as header names. This used to be X_UTME, Y_UTMN, etc. This implementation makes the plugin work with both headers.
---

Update ``SwatinitQC`` so it works with new header for polygon files.

---

CHANGELOG.md
webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_utils/_map_figure.py

By default, datatio writes X, Y, Z, ID as header names. This used to be X_UTME, Y_UTMN, etc. This implementation makes the plugin work with both headers.

Update ``RftPlotter`` so it works with new header for polygon files.

---

webviz_subsurface/plugins/_parameter_analysis/_views/_parameter_response_view/_view.py
webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_view.py

The uuid of the parameter filter in `ParamAnalysis` and `RftPlotter` was not handled in the correct way. This PR fixes that bug:
---

Bugfix in ParameterFilter in `ParamAnalysis` and `RftPlotter`

---

CHANGELOG.md
tests/integration_tests/test_parameter_filter.py
webviz_subsurface/_components/parameter_filter.py
webviz_subsurface/_figures/timeseries_figure.py
webviz_subsurface/_models/parameter_model.py
webviz_subsurface/plugins/_parameter_analysis/_plugin.py
webviz_subsurface/plugins/_parameter_analysis/_utils/_parameters_model.py
webviz_subsurface/plugins/_parameter_analysis/_utils/_provider_timesseries_datamodel.py
webviz_subsurface/plugins/_parameter_analysis/_views/_parameter_response_view/_settings/_parameter_filter.py
webviz_subsurface/plugins/_parameter_analysis/_views/_parameter_response_view/_settings/_selections.py
webviz_subsurface/plugins/_parameter_analysis/_views/_parameter_response_view/_settings/_vizualisation.py
webviz_subsurface/plugins/_parameter_analysis/_views/_parameter_response_view/_view.py
webviz_subsurface/plugins/_rft_plotter/_utils/_rft_plotter_data_model.py

New functionality in the `ParameterAnalysis` plugin:
- Observations in time series plot. Can be turned on and off in the visualization settings. New input parameter `obsfile`, exactly as in the `SimulationTimeSeries` plugin.
- Possibility to change resampling frequency. The already existing input parameter `time_index` will be used as starting point. There is a new parameter `perform_presampling` (as in `SimulationTimeSeries`) that is default False. If that is set to true, `time_index` is used as the presampling frequency.
- Sensitivity filter in the parameter filter (If `SENSNAME` exists as a parameter in any of the ensembles, it will show up as the top of the parameters list)
---

New functionality in `ParameterAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_rft_plotter/_plugin.py
webviz_subsurface/plugins/_rft_plotter/_utils/_formation_figure.py
webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_utils/_map_figure.py
webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_settings/_parameter_filter.py
webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_settings/_selections.py
webviz_subsurface/plugins/_rft_plotter/_views/_parameter_response_view/_view.py

All ensembles are now displayed in the parameter response view. Not only the ones that are labelled monte carlo. Instead there is now a sensitivity filter in the parameter filter. If `SENSNAME` exists as a parameter in any of the ensembles, it will show up as the top of the parameters list.
---

Sensitivity filter in `RftPlotter` parameter response view

---

webviz_subsurface/plugins/_parameter_analysis/_views/_parameter_response_view/_view.py

When the selected vector was also included in the list of vectors for parameter correlation then it was duplicated in the list passed to the summary provider. This gave an error. F.ex if the selected vector is `FOPT` and the correlation vector is `F*`. The solution is to remove duplicates from the list.
---

Bugfiz in `ParameterAnalysis`

---

CHANGELOG.md
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py

This PR fixes some bugs in the `VolumetricAnalysis` plugin:
- Bug in the statistics table that made the selector columns be merged. Bug introduced in #1116  
- Error was raised when no groups were selected for a bar chart
- Runtime warning was given when statistics was run on a column with only nan values

Bugfixes in `VolumetricAnalysis`

---

.github/workflows/subsurface.yml
mypy.ini
setup.py
tests/unit_tests/model_tests/test_well_set_model.py
webviz_subsurface/_providers/ensemble_grid_provider/grid_viz_service.py
webviz_subsurface/_providers/ensemble_surface_provider/surface_array_server.py
webviz_subsurface/_providers/ensemble_surface_provider/surface_image_server.py
webviz_subsurface/plugins/_map_viewer_fmu/map_viewer_fmu.py

PR that fixes the failing CI tests, and enables mypy in the CI again.
Tests were failing due to pyscal removing the dependencies on scipy<1.93 https://github.com/equinor/pyscal/pull/401. This led Scipy to be updated, using an improved interpolation algorithm which led to the assertion error. 
It was also needed to unpin the xtgeo version to include a bugfix https://github.com/equinor/xtgeo/pull/822

Fix CI and enable mypy again

---

CHANGELOG.md
webviz_subsurface/plugins/_simulation_time_series_onebyone/_utils/_simulation_time_series_onebyone_datamodel.py
webviz_subsurface/plugins/_simulation_time_series_onebyone/_views/_onebyone_view/_settings/_sensitivity_filter.py
webviz_subsurface/plugins/_simulation_time_series_onebyone/_views/_onebyone_view/_view.py

PR that adds the option to use the sensitivity filter on all elements or only the timeseries graph in the `SimulationTimeseriesOneByOne` plugin.
- deafault behaviour is set to use the filter across all visualisations
Solves #1224

Add filter linking in `SimulationTimeseriesOneByOne`

---

webviz_subsurface/plugins/_rft_plotter/_plugin.py
webviz_subsurface/plugins/_rft_plotter/_utils/_rft_plotter_data_model.py
webviz_subsurface/plugins/_rft_plotter/_views/_qc_view/__init__.py
webviz_subsurface/plugins/_rft_plotter/_views/_qc_view/_settings.py
webviz_subsurface/plugins/_rft_plotter/_views/_qc_view/_table_view_element.py
webviz_subsurface/plugins/_rft_plotter/_views/_qc_view/_view.py

New view in `RftPlotter` that displays the data in a data table. Valuable for QC of de-activated data points.
---

QC Data view in `RftPlotter`

---

CHANGELOG.md
webviz_subsurface/plugins/_rft_plotter/_utils/_rft_plotter_data_model.py
webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_settings/_map_settings.py
webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_utils/_map_figure.py
webviz_subsurface/plugins/_rft_plotter/_views/_map_view/_view.py

PR to get rid of a very slow pandas apply function in the `RftPlotter`. In one medium sized project this function took 37 sec 😲 
The code is now improved and does no longer require this function.
The function in question:
```       
self.ertdatadf["DATE_IDX"] = self.ertdatadf["DATE"].apply(
lambda x: list(self.ertdatadf["DATE"].unique()).index(x)
)
```
Small additional feature
- the selected date filter has been added as title in the map.
- the date has been added as hover info per RFT point in the map.
- Removed FutureWarning from pandas by dropping the `ZONE` column before doing a `groupby.mean()`

Remove slow performant function in RftPlotter

---

CHANGELOG.md
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/_providers/ensemble_summary_provider/_csv_import.py
webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider_factory.py
webviz_subsurface/_providers/ensemble_table_provider/_table_import.py
webviz_subsurface/_providers/ensemble_table_provider/ensemble_table_provider_factory.py
webviz_subsurface/_utils/ensemble_table_provider_set.py
webviz_subsurface/_utils/ensemble_table_provider_set_factory.py
webviz_subsurface/_utils/formatting.py
webviz_subsurface/plugins/_parameter_analysis/_plugin.py
webviz_subsurface/plugins/_parameter_response_correlation.py
webviz_subsurface/plugins/_property_statistics/property_statistics.py
webviz_subsurface/plugins/_rft_plotter/_utils/_rft_plotter_data_model.py
webviz_subsurface/plugins/_simulation_time_series_onebyone/_plugin.py
webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py

PR with improvements to the `EnsembleTableProvider` which leads to improved start up time of an `Webviz` instance.
Main issue with the current `EnsembleTableProvider` was that it was initializing a `ScratchEnsemble` for every unique csv-file/parameters in each unique ensemble, instead of using a cached `ScratchEnsemble`. This was time consuming and not very memory friendly.
This PR includes:
- Removal of the `fmu-ensemble` dependency in the `EnsembleTableProvider`. 
- `fmu-ensemble` was used only for loading csvfiles into dataframes, and loading parameters into dataframe. This functionality is now included in this PR instead, and is based alot on exising functionality from the `EnsembleSummaryProvider`
- The functionality from `fmu-ensemble` to filter on successful realization has been …

Improved performance of `EnsembleTableProvider`

---

CHANGELOG.md
webviz_subsurface/_models/parameter_model.py
webviz_subsurface/_providers/ensemble_table_provider/_table_import.py
webviz_subsurface/_providers/ensemble_table_provider/ensemble_table_provider_factory.py
webviz_subsurface/plugins/_simulation_time_series_onebyone/_views/_onebyone_view/_view.py

PR with some bugfixes:
- Bugfix in the `EnsembleTableProvider` to allow spaces in parameter values, when loading parameters.txt. (e.g in a sensitivity name). 
- This change is done on a unreleased feature, hence no changelog entry.
- Bugfixes in the `SimulationTimeseriesOneByOne` 
- Change selected sensitivity filter values when ensemble is changed. Closes #1228
- Here the new feature in Dash to allow for duplicate outputs in callbacks has been utilized to avoid combining two callbacks into one.
- Prevent update if no sensitivities have been selected in the sensitivity filter
- Avoid Error if no sensitivity ensembles are input to the plugin
- handled by allowing existing functionality in the `ParametersModel `to insert values for `SENSNAME/SENSCASE`

Bugfixes in the `EnsembleTableProvider` and `SimulationTimeseriesOneByOne`

---

webviz_subsurface/plugins/_well_completion/_utils/_well_completion_data_model.py

Small bugfix. The `zones` property needs to be a list and not an `ndarray` or it causes some unexpected behavoir in line 130 where the list is used as a boolean. 
---

Small bugfix in WellCompletion

---

webviz_subsurface/plugins/_co2_leakage/_plugin.py
webviz_subsurface/plugins/_co2_leakage/_utilities/callbacks.py
webviz_subsurface/plugins/_co2_leakage/_utilities/co2volume.py
webviz_subsurface/plugins/_co2_leakage/_utilities/color_tables.py
webviz_subsurface/plugins/_co2_leakage/_utilities/generic.py
webviz_subsurface/plugins/_co2_leakage/_utilities/initialization.py
webviz_subsurface/plugins/_co2_leakage/_utilities/summary_graphs.py
webviz_subsurface/plugins/_co2_leakage/views/mainview/mainview.py
webviz_subsurface/plugins/_co2_leakage/views/mainview/settings.py

The script generating CO2 containment data was updated and this commit ensures that the new format is read and presented properly. This includes:
- Hide the plots if the data fails to load or is missing
- CO2 amounts can be scaled to Mtons/fraction
- Updated default 'map_attributes_names' to be consistent with recent changes in xtgeoapp_grd3dmaps
- Parsing and visualization of boundary polygon has been improved
- New "UNSMRY" plot aimed to show unified summary data from Pflotran or Eclipse
- Support for visualizing multi polygon boundary files
Other improvements:
- Added option of hazardous polygon. This creates a new category "hazardous" in the containment plots (colored red). Changed color of "outside" from red to blue and color of "inside" from blue to green.
- Removed mobile gas plot …

CO2Leakage: Improve containment plots

---

webviz_subsurface/plugins/_simulation_time_series/_plugin.py
webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_settings/_resampling_frequency.py
webviz_subsurface/plugins/_simulation_time_series/_views/_subplot_view/_view.py

When plugin was configured with `perform_presampling: true`, the active presamling frequency was passed to the presampled ensemble summary providers when looking for dates. This is incorrect and prevented by not retrieving dates for presampled providers. 
The dates was retrieved for usage in "Data relative to date" selection. As this calculation is dependent of equal vector length handled by extrapolation/interpolation functionality in providers, it is disabled for presampled providers.

Fix bug for `perform_presampling: true` in `SimulationTimeSeries`

---

CHANGELOG.md
webviz_subsurface/plugins/_co2_leakage/_plugin.py
webviz_subsurface/plugins/_co2_leakage/_utilities/callbacks.py
webviz_subsurface/plugins/_co2_leakage/_utilities/generic.py
webviz_subsurface/plugins/_co2_leakage/views/mainview/settings.py

Added button "OPTIONS AND GLOBAL FILTERS", similar to MapViewer.
Also changed default color scale to turbo and changed default formation to "All" instead of the first one alphabetically.
---

CO2Leakage: Add options-button for plotting polygons and fault lines, plus some minor visual changes

---

CHANGELOG.md
webviz_subsurface/_figures/px_figure.py
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/utils/table_and_figure_utils.py
webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py

PR that adds new functionality to compute facies fractions per individual facies in the `VolumetricAnalysis` plugin.
To compute facies fractions, FACIES needs to be included as a groupby selector. To inform users text is outputted to the screen.
The fractions is calculated as the sum of bulk for a facies divided by the total bulk sum - this gives exact results as weighting on bulk volumes inside RMS.
Other smaller improvements in this PR:
- added text label to bar plots, and possibility to control the number formatting from settings. Note the Default option will try to guess the format based on the selected responses.
- added more fluid representative coloring to plots if the "FLUID_ZONE" is used as Color by. 
Other smaller bug fixes in this PR:
- ensure that the boxmode is always valid …

Added facies fractions to `VolumetricAnalysis` and smaller bugfixes

---

setup.py
webviz_subsurface/plugins/_group_tree/_utils/_ensemble_group_tree_data.py
webviz_subsurface/plugins/_group_tree/_views/_group_tree_view/_view.py

Adjustments to match: https://github.com/equinor/webviz-subsurface-components/pull/1794
----
Await new release of `wsc` before finalizing this PR.

Adjust naming according to new property names after splitting GroupTree-component view/settings

---

webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/utils/table_and_figure_utils.py
webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py

PR to add statistical lines with Mean/p10/p90 to histograms in `VolumetricAnalysis` 
Option to turn them off, or select only the mean line has been added to "Settings"

Add statlines to histogram in `VolumetricAnalysis` 

---

CHANGELOG.md
setup.py
tests/unit_tests/provider_tests/test_ensemble_summary_provider.py
webviz_subsurface/_datainput/fmu_input.py
webviz_subsurface/_datainput/history_match.py
webviz_subsurface/_datainput/pvt_data.py
webviz_subsurface/_datainput/relative_permeability.py
webviz_subsurface/_datainput/well_completions.py
webviz_subsurface/_models/ensemble_model.py
webviz_subsurface/_models/gruptree_model.py
webviz_subsurface/_providers/ensemble_fault_polygons_provider/_fault_polygons_discovery.py
webviz_subsurface/_providers/ensemble_summary_provider/_field_metadata.py
webviz_subsurface/_providers/ensemble_summary_provider/dev_compare_fmu_to_lazy_provider.py
webviz_subsurface/_providers/ensemble_surface_provider/_surface_discovery.py
webviz_subsurface/plugins/_group_tree/_plugin.py
webviz_subsurface/plugins/_parameter_analysis/_plugin.py
webviz_subsurface/plugins/_prod_misfit/_plugin.py
webviz_subsurface/plugins/_property_statistics/property_statistics.py
webviz_subsurface/plugins/_pvt_plot/_plugin.py
webviz_subsurface/plugins/_relative_permeability.py
webviz_subsurface/plugins/_rft_plotter/_plugin.py
webviz_subsurface/plugins/_vfp_analysis/_plugin.py
webviz_subsurface/plugins/_vfp_analysis/_utils/_vfp_data_model.py
webviz_subsurface/plugins/_well_analysis/_plugin.py
webviz_subsurface/plugins/_well_completion/_plugin.py
webviz_subsurface/plugins/_well_completions/_business_logic.py
webviz_subsurface/plugins/_well_completions/_plugin.py
webviz_subsurface/smry2arrow_batch.py

Closes https://github.com/equinor/webviz-subsurface/issues/1249.

Rename from `ecl2df` to `res2df`

---

setup.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
webviz_subsurface/_datainput/pvt_data.py

It seems like there is an error importing `opm` in Docker Python 3.8 for some reason. Since we use `try/except` to support Windows/MacOS we do not get the traceback and the CI tests do not fail.
Trying to change from `try/except` to explicitly saying we only want `opm` to be imported if platform is Linux.

Avoid `try/except` on `import`

---

setup.py

Related to https://github.com/equinor/webviz-subsurface/issues/1258.

Reverting `opm` unpinning due to current Docker image incompatibility

---

webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/utils/table_and_figure_utils.py
webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py

PR which resolves #1264, and adds waterfall plots for analyzing a volumetric change to the existing `comparison` tabs in `VolumetricAnalysis` .
The waterfall plot functionality is only supported for static volumes, and will only work for STOIIP or GIIP response.
If a `NET` column is present in the dataset `NTG` and `PORO_NET` will be used in the waterfall plot otherwise the `PORO `column is used.
The waterfall functionality will work both for `ensemble`, `source` and `sensitivity` volumes comparisons.

Add volume change analysis plot to VolumetricAnalysis

---

.github/workflows/subsurface.yml

We run linting and tests on code changes, but could argue that these are not as necessary when creating a tag (on existing code base).

Do not run linting and tests on release

---

webviz_subsurface/plugins/_map_viewer_fmu/_utils.py

This issue closes #1273 
The affected code seems to be correct;
https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.Draw
These mypy reported errors was introduced when updating to Pillow 10.3.0 https://pypi.org/project/pillow/10.3.0/
This will clog the daily builds for webviz-subsurface repo.
---

Add ignores to mypy false positives

---

README.md

These stopped working back in 2022.
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
Resolves #1279
---

Remove non-working lgtm badges

---

.github/workflows/subsurface.yml

Werkzeug issue was resolved in dash: https://github.com/plotly/dash/pull/1995
Bleach issue resolved: https://github.com/equinor/webviz-config/pull/588
---

Unpin selenium, bleach and werkzeug

---

CHANGELOG.md
webviz_subsurface/_models/inplace_volumes_model.py
webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py

Add automatic calculation of `STOIIP_TOTAL` and `GIIP_TOTAL` columns to `VolumetricAnalysis`.
Drogon example:
Also included a bugfix on the logic for evaluating if the data is compatible for a water fall plot

Add column with total oil/gas volumes to VolumetricAnalysis

---

.github/workflows/subsurface.yml
CHANGELOG.md
webviz_subsurface/plugins/_co2_leakage/_plugin.py
webviz_subsurface/plugins/_co2_leakage/_utilities/callbacks.py
webviz_subsurface/plugins/_co2_leakage/_utilities/co2volume.py
webviz_subsurface/plugins/_co2_leakage/_utilities/generic.py
webviz_subsurface/plugins/_co2_leakage/_utilities/initialization.py
webviz_subsurface/plugins/_co2_leakage/_utilities/surface_publishing.py
webviz_subsurface/plugins/_co2_leakage/views/mainview/settings.py

Major changes:
- Input format of csv-files from ccs-scripts with containment information is changed
- Added support for visualization of residual trapping if included in files from ccs-scripts
- Migration time maps now supported also for AMFG property
Minor changes:
- Improvements to hover information in containment plots
- Improvements to warnings given for missing map files
The failing tests depend on PR https://github.com/equinor/webviz-subsurface-testdata/pull/148. This updates the tests with the new format and needs to be merged first.

CO2Leakage: Add support for residual trapping and AMFG migration time

---

webviz_subsurface/plugins/_rft_plotter/_utils/_rft_plotter_data_model.py

Improved Error message in the corner case that there is no active RFTs in the input data. F.ex if all the RFTs are inactivated due to zone mismatch.
---

No Active Rfts error message

---

webviz_subsurface/_datainput/well_completions.py

Resolves problem where:
```
----> 1 from res2df.resdatafiles import common
ImportError: cannot import name 'common' from 'res2df.resdatafiles' (/prog/res/komodo/2025.04.01-py311-rhel8/root/lib64/python3.11/site-packages/res2df/resdatafiles.py)
```
---

Fix res2df import common
