- README.md
- webviz_subsurface/containers/_history_match.py
- webviz_subsurface/containers/_parameter_distribution.py
Remove unused code, some markup fixes in `README`, changing to static class methods where possible, and renaming potential name conflict.
Add badges (pypi, travis, codacy, python version).
> Improve code style

- .travis.yml
- setup.py
> Update chrome driver used in Travis

- webviz_subsurface/datainput/__init__.py
Data input for the HM container has changed. We drop the input column with zero misfit iff it exists (as that contributes nothing to the visual anyway - averages are still calculated based on total number of observation points).
> Data input changed for HM container

- setup.py
- webviz_subsurface/containers/_subsurface_map.py
Related to https://github.com/equinor/webviz-subsurface-components/pull/7.
Resolves #17.
> Reduce data size Map

- examples/basic_example.yaml
- tests/test_parameter_distribution.py
- webviz_subsurface/containers/_disk_usage.py
- webviz_subsurface/containers/_history_match.py
- webviz_subsurface/containers/_intersect.py
- webviz_subsurface/containers/_morris_plot.py
- webviz_subsurface/containers/_parameter_distribution.py
- webviz_subsurface/containers/_subsurface_map.py
- webviz_subsurface/containers/_summary_stats.py
Update according to changes in https://github.com/equinor/webviz-config/pull/32.
> Update to abc class

- webviz_subsurface/containers/_disk_usage.py
- webviz_subsurface/containers/_history_match.py
- webviz_subsurface/containers/_morris_plot.py
- webviz_subsurface/containers/_subsurface_map.py
- webviz_subsurface/containers/_summary_stats.py
> Remove user provided container titles

- webviz_subsurface/containers/_summary_stats.py
> Change CheckList syntax from values to value

- webviz_subsurface/containers/_disk_usage.py
- webviz_subsurface/containers/_inplace_volumes.py
- webviz_subsurface/containers/_intersect.py
- webviz_subsurface/containers/_parameter_distribution.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
Following https://github.com/equinor/webviz-core-components/pull/12 replace use of `dash_core_components.Graph()` with `webviz_core_components.Graph()`
> Use Plotly graph from webviz-core-components

- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
> Show realization in simulation time series

- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
> Improve docstring simulation time series container

- examples/basic_example.yaml
- setup.py
- webviz_subsurface/containers/__init__.py
- webviz_subsurface/containers/_parameter_distribution.py
- webviz_subsurface/datainput/__init__.py
- webviz_subsurface/datainput/_fmu_input.py
Added ParameterDistribution container that shows multiple ensembles of model parameters in histogram/boxplot
> Added parameter distribution container

- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
> Download selected vector

- examples/basic_example.yaml
- setup.py
- webviz_subsurface/containers/__init__.py
- webviz_subsurface/containers/_inplace_volumes_onebyone.py
- webviz_subsurface/datainput/_inplace_volumes.py
- webviz_subsurface/private_containers/_tornado_plot.py
Closes #94 
- Added tornadoplot that can be used in different dashboards.
- Added in place volumetrics dashboard with tornadoplot for ensembles using design matrix
> Tornado plot

- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
- webviz_subsurface/datainput/__init__.py
- webviz_subsurface/datainput/_reservoir_simulation_timeseries.py
and add back reservoirsimulationtimeseries functions.
> Fix cyclic imports

- setup.py
- webviz_subsurface/containers/_inplace_volumes_onebyone.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries_onebyone.py
Added tours for:
- InplaceVolumesOneByOne
- ReservoirSimulationTimeSeriesOneByOne
> Guided tours for containers

- webviz_subsurface/containers/_parameter_correlation.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries_onebyone.py
- webviz_subsurface/private_containers/_tornado_plot.py
> Highlight selected date on chart

- webviz_subsurface/datainput/_inplace_volumes.py
- webviz_subsurface/private_containers/_tornado_plot.py
> Improved error description for missing volumetrics or sensitivity input data

- examples/basic_example.yaml
- setup.py
- webviz_subsurface/containers/__init__.py
- webviz_subsurface/containers/_segy_viewer.py
- webviz_subsurface/datainput/_seismic.py
> SEG-Y viewer

- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
> Use new plotly.subplots methods

- webviz_subsurface/containers/_segy_viewer.py
> Better default values for SegyViewer

- webviz_subsurface/datainput/_surface.py
> Display max value in WellCrossSection map view

- .travis.yml
- setup.py
- tests/integration_tests/test_aggregated_data_example.py
- webviz_subsurface/containers/_segy_viewer.py
- Use ColorScales component from webviz-core-components
- Add SegyViewer to aggregated example test
> Use wcc.colorscales component

- webviz_subsurface/_private_containers/tornado_plot.py
- webviz_subsurface/containers/_inplace_volumes.py
- webviz_subsurface/containers/_inplace_volumes_onebyone.py
- webviz_subsurface/containers/_parameter_distribution.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries_onebyone.py
- webviz_subsurface/containers/_segy_viewer.py
Relates to #154 
- Fixed ids and added tour for most containers.
- Fixed small issue with shared x-axis for ReservoirSimTimeSeries (logic changed with new plotly version)
Tour for ParameterCorrelation and CrossSection will be handled in separate PR along with some improvements.
> Add missing tour steps for containers

- .travis.yml
- tests/integration_tests/test_parameter_corr.py
- webviz_subsurface/__init__.py
- webviz_subsurface/containers/__init__.py
- webviz_subsurface/containers/_history_match.py
- webviz_subsurface/containers/_inplace_volumes.py
- webviz_subsurface/containers/_inplace_volumes_onebyone.py
- webviz_subsurface/containers/_parameter_correlation.py
- webviz_subsurface/containers/_parameter_distribution.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries_onebyone.py
- webviz_subsurface/containers/_subsurface_map.py
The aim of this PR is to use the new feature introduced in https://github.com/equinor/webviz-config/pull/162.
Closes #128.
> Check and verify shared_settings

- .travis.yml
- setup.py
- webviz_subsurface/__init__.py
> Do not raise error if ensemble path does not exist in portable run

- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
> Removed observation visualizations in delta mode

- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
> Label mean on mean trace

- .travis.yml
- webviz_subsurface/_datainput/fmu_input.py
- webviz_subsurface/_datainput/history_match.py
- webviz_subsurface/_datainput/inplace_volumes.py
- webviz_subsurface/containers/_history_match.py
- webviz_subsurface/containers/_inplace_volumes.py
- webviz_subsurface/containers/_inplace_volumes_onebyone.py
- webviz_subsurface/containers/_parameter_distribution.py
- webviz_subsurface/containers/_parameter_response_correlation.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries.py
- webviz_subsurface/containers/_reservoir_simulation_timeseries_onebyone.py
Followup of https://github.com/equinor/webviz-config/pull/167.
> Simplification after webviz-store supporting mutable instances

- setup.py
- tests/integration_tests/test_parameter_corr.py
- webviz_subsurface/containers/_parameter_correlation.py
Fixed heatmap layout issue and simplified container code.
Replaced `dash_daq.toggleSwitch` with a `dcc.CheckList` and removed `dash_daq` dependency.
Closes #159
> Parameter correlation fixes

- webviz_subsurface/plugins/_history_match.py
Closes #183.
Before this PR, the ensemble-name ordering present in the returned DataFrame from `fmu-ensemble` was used. Changed this such that user provided input order is used instead.
> Use input order of ensembles in HM plot

- webviz_subsurface/__init__.py
- webviz_subsurface/_abbreviations/__init__.py
- webviz_subsurface/_datainput/xsection.py
- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/plugins/_inplace_volumes_onebyone.py
- Fixes some lgtm.com reported warnings.
- Closes #204.
> Various small fixes

- webviz_subsurface/_datainput/surface.py
- webviz_subsurface/plugins/_well_cross_section_fmu.py
- Calculate bounds from unrotated surface
- Fill masked np array with nan values before dumping to file
> Small fixes to surface calculations

- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Better detection of historical vector names

- webviz_subsurface/plugins/_segy_viewer.py
Closes #218 
Some minor layout improvements.
> Improve SEG-Y Viewer axis scaling

- .gitignore
- webviz_subsurface/plugins/_parameter_correlation.py
- webviz_subsurface/plugins/_parameter_response_correlation.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_segy_viewer.py
- webviz_subsurface/plugins/_surface_with_grid_cross_section.py
- webviz_subsurface/plugins/_surface_with_seismic_cross_section.py
> Changed theme in plugins

- setup.py
- webviz_subsurface/plugins/_parameter_distribution.py
Closes #31. Related to https://github.com/equinor/webviz-subsurface-components/pull/103.
> Prior-posterior distribution

- webviz_subsurface/_private_plugins/tornado_plot.py
- webviz_subsurface/plugins/_inplace_volumes_onebyone.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
> Make one boxplot trace per senscase and some minor fixes

- .travis.yml
- setup.py
- tests/integration_tests/test_surface_selector.py
- webviz_subsurface/_datainput/fmu_input.py
- webviz_subsurface/_datainput/surface.py
- webviz_subsurface/_datainput/well.py
- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_surface_viewer_fmu.py
> Surface viewer FMU

- webviz_subsurface/_datainput/fmu_input.py
> Default filter ensembles on existence of OK file

- setup.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_parameter_parallel_coordinates.py
> Parameters parallel coordinates

- .github/workflows/webviz-subsurface.yml
See [this post](https://github.community/t5/GitHub-Actions/GitHub-Actions-branch-conditional/td-p/29794) for details.
> Correct github.ref in GitHub action

- .github/workflows/webviz-subsurface.yml
- .travis.yml
GitHub workflow has some issues, in the sense that it is not always triggered (looks to be dependent on which users that creates the initial PR that is pushed to). Needs to be investigated, adding back Travis.
> Add back Travis

- webviz_subsurface/_private_plugins/tornado_plot.py
> Tornadoplot: Shift bar base when both cases have same sign

- webviz_subsurface/plugins/_parameter_parallel_coordinates.py
> Select all ensembles initially in parallel coordinates

- webviz_subsurface/plugins/_inplace_volumes_onebyone.py
> Increased width of response drop-down

- .travis.yml
- webviz_subsurface/plugins/_inplace_volumes_onebyone.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
> Use aggregated parameters for tornado. Increase tornado width

- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Nonexisting vector error message

- webviz_subsurface/_datainput/fmu_input.py
- webviz_subsurface/plugins/_history_match.py
- webviz_subsurface/plugins/_parameter_correlation.py
- webviz_subsurface/plugins/_parameter_parallel_coordinates.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
- webviz_subsurface/plugins/_surface_viewer_fmu.py
- webviz_subsurface/plugins/_well_cross_section_fmu.py
> Additional type hints

- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
Closes #210 
Will probably change again with #284, but that change is more general.
> Fix missing history trace for timeseries statistics

- webviz_subsurface/plugins/_inplace_volumes.py
> Inplace volumetrics: Initialize with boxplot if multiple ensembles are present

- .github/workflows/webviz-subsurface.yml
- setup.py
- webviz_subsurface/_datainput/relative_permeability.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_relative_permeability.py
> Relative permeability

- webviz_subsurface/_private_plugins/tornado_plot.py
> TornadoPlot: Include all parameter label ticks on y-axis

- webviz_subsurface/plugins/_parameter_parallel_coordinates.py
> Bugfix: webvizstore added to ParameterParallelCoordinates

- .github/workflows/webviz-subsurface.yml
- setup.py
- webviz_subsurface/_datainput/fmu_input.py
- webviz_subsurface/_datainput/history_match.py
- webviz_subsurface/_datainput/inplace_volumes.py
Follow-up of https://github.com/equinor/fmu-ensemble/pull/130.
> Relax version constraint dependencies, add fmu-ensemble as dependency

- .github/workflows/webviz-subsurface.yml
> Clean Ubuntu GH workflow image

- .github/workflows/webviz-subsurface.yml
- setup.py
> Set dash to <=1.10

- .github/workflows/webviz-subsurface.yml
- webviz_subsurface/_datainput/xsection.py
- webviz_subsurface/plugins/_running_time_analysis_fmu.py
- webviz_subsurface/plugins/_surface_viewer_fmu.py
> linting pylint 2.5.0

- webviz_subsurface/_private_plugins/tornado_plot.py
> Tornado plot tooltip realizations as integers

- webviz_subsurface/_private_plugins/tornado_plot.py
> Switch from radiobutton to checkbox

- webviz_subsurface/_abbreviations/reservoir_simulation.py
1. Deactivates the description warnings for UDQs as originally requested in #321
-Does not implement the additional suggestions on user defined UDQ descriptions.
2. Fixes issue with well completion keyword descriptions (e.g. WOPRL) that was discovered during testing of point 1.
> Improved vector description for completions and UDQs

- .github/workflows/webviz-subsurface.yml
> Improve GitHub workflow config

- tests/unit_tests/plugin_tests/test_tornado_functions.py
- webviz_subsurface/_private_plugins/tornado_plot.py
> Correct realizations in TornadoPlot tooltip

- webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
Changed to None to reduce risk of "double storing" data during portable build (if e.g. the ReservoirSimulationTimeSeries plugin is also used).
> Changed default column_keys in ReservoirSimulationTimeSeriesRegional to None

- webviz_subsurface/_private_plugins/tornado_plot.py
> TornadoPlot hovermode set to y

- webviz_subsurface/plugins/_inplace_volumes_onebyone.py
Resolves #355  
New order of callbacks is: render tornado and table -> render graph (as it is dependent on tornado state)
Additional changes were made as several minor issues were observed during testing: 
- If plotting bar chart per realization, the bar colors were not updated on change of filters and selectors, only on tornado plot click (similar issue as #339)
- Bar chart colors when selecting sensitivity in tornado plot were hard coded, therefore not following theme (which the TornadoPlot on the other hand does). Changed to follow theme.
- Swtiched `ids `to `uuid` from `webviz-config`
- Theme added to box plot views, was using some default coloring.
> Reformat InplaceVolumesOneByOne to avoid double callback to output + some minor additional changes

- webviz_subsurface/_datainput/inplace_volumes.py
Resolves #354   
Due to change upstream in `fmu-ensemble`
> Change to ignore KeyError in _datainput/inplace_volumes

- webviz_subsurface/plugins/_parameter_response_correlation.py
Resolves #346
Additionally: Empty "distribution graph" (the scatter and historgram plots) instead of `PreventUpdate` when changing to a filter combination that doesn't work, similar to the "correlation graph" (the tornado plot)
> ParameterResponseCorrelation responses from UNSMRY

- webviz_subsurface/_private_plugins/tornado_plot.py
Note that I also refactored calculation of the DataFrame out of the `tornado_plot` method, as the `tornado_plot` method was beginning to get quite long.
> TornadoPlot modifications from user feedback

- setup.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_multiple_regression.py
- webviz_subsurface/plugins/_multiple_regression_sofie.py
- webviz_subsurface/plugins/_p_values.py
(So that each group member can make their own version of the plugin)
> Add 'Sofie' to the plugin name

- webviz_subsurface/plugins/_disk_usage.py
Resolves #374 
Included some other minor updates like uuid and theming.
This edit is breaking in the way that the old format is not supported, but I don't believe it is an issue.
> Update DiskUsage to newer standard file location and format

- webviz_subsurface/_private_plugins/tornado_plot.py
> Filter tornado sensitivities

- setup.py
> Add Dash to setup.py

- webviz_subsurface/_utils/simulation_timeseries.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Improved verification of observation file for time series observations.

- .github/workflows/subsurface.yml
- tests/integration_tests/test_aggregated_data_example.py
- tests/integration_tests/test_raw_data_example.py
Followup of https://github.com/equinor/webviz-subsurface-testdata/pull/51.
> Use new example configuration names

- setup.py
- webviz_subsurface/_abbreviations/number_formatting.py
- webviz_subsurface/_abbreviations/reservoir_simulation.py
- webviz_subsurface/_datainput/from_timeseries_cumulatives.py
- webviz_subsurface/_datainput/relative_permeability.py
- webviz_subsurface/_datainput/surface.py
- webviz_subsurface/_datainput/well.py
- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/_private_plugins/tornado_plot.py
- webviz_subsurface/_utils/parameter_response.py
- webviz_subsurface/plugins/_disk_usage.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_table.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_xsection.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py
- webviz_subsurface/plugins/_parameter_correlation.py
- webviz_subsurface/plugins/_parameter_parallel_coordinates.py
- webviz_subsurface/plugins/_parameter_response_correlation.py
- webviz_subsurface/plugins/_relative_permeability.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
- webviz_subsurface/plugins/_rft_plotter/_crossplot_figure.py
- webviz_subsurface/plugins/_rft_plotter/_formation_figure.py
- webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
- webviz_subsurface/plugins/_running_time_analysis_fmu.py
- webviz_subsurface/plugins/_segy_viewer.py
- webviz_subsurface/plugins/_surface_with_grid_cross_section.py
- webviz_subsurface/plugins/_surface_with_seismic_cross_section.py
- webviz_subsurface/plugins/_well_cross_section.py
- webviz_subsurface/plugins/_well_cross_section_fmu.py
Code style updates to get 🟢 from new `black` version
---
> black 20.8b1 updates

- CHANGELOG.md
Changed typo in release date of 0.1.2 from 2020-09-24 to 2020-08-24.
> Changed release date of 0.1.0 in CHANGELOG to 2020-08-24

- setup.py
- webviz_subsurface/_datainput/opm_init_io.py
- webviz_subsurface/_datainput/pvt_data.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_pvt_plot.py
Moved data frame filtering to pvt_data.py so that it can be cached.
Moved the dropping of duplicate ensembles to a feature flag in the plugin's config.
Merged 'master' into this branch.
(This branch is based on the changes of the pvt-plot-plugin branch.)
> Created a plugin for extracting, filtering and visualizing PVT data.

- CHANGELOG.md
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Only strip on match of full string in unit_vec

- CHANGELOG.md
- webviz_subsurface/plugins/_relative_permeability.py
---
- ~~[ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.~~
> Improve relperm documentation

- CHANGELOG.md
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- ~[ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.~
> Use correct real number in ReservoirSimulationTimeSeries hover

- CHANGELOG.md
- webviz_subsurface/plugins/_running_time_analysis_fmu.py
- webviz_subsurface/plugins/_well_cross_section_fmu.py
> Remove use of pandas objects in stored functions

- webviz_subsurface/plugins/_parameter_correlation.py
> Remove pandas FutureWarning by retaining current behaviour

- tests/integration_tests/test_aggregated_data_example.py
- tests/integration_tests/test_raw_data_example.py
Followup of https://github.com/equinor/webviz-config/pull/230.
> Update page ids (replace _ with -)

- setup.py
- webviz_subsurface/plugins/__init__.py
- Make list alphabetic.
- Don't split long lines with `+` etc. (less readable).
> Maintenance setup.py + __init__.py

- CHANGELOG.md
- webviz_subsurface/plugins/_parameter_correlation.py
> Drop constant parameters from ParameterCorrelation

- webviz_subsurface/plugins/_rft_plotter/_crossplot_figure.py
- webviz_subsurface/plugins/_rft_plotter/_formation_figure.py
- webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
This will prepare webviz for a possible upcoming change in
scripts generating the input to the rft plotter plugin.
This change should be backwards compatible.
---
> Extend column name obs->observed for readability

- CHANGELOG.md
- setup.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_bhp_qc.py
> BHP QC viewer

- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Remove hard coded heights

- CHANGELOG.md
- webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
> Sort rft dataframe by dates

- CHANGELOG.md
- setup.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_parameter_analysis/__init__.py
- webviz_subsurface/plugins/_parameter_analysis/controllers/__init__.py
- webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_qc_controller.py
- webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
- webviz_subsurface/plugins/_parameter_analysis/data_loaders/__init__.py
- webviz_subsurface/plugins/_parameter_analysis/figures/color_figure.py
- webviz_subsurface/plugins/_parameter_analysis/figures/correlation_figure.py
- webviz_subsurface/plugins/_parameter_analysis/models/__init__.py
- webviz_subsurface/plugins/_parameter_analysis/models/ensemble_set_model.py
- webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
- webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
- webviz_subsurface/plugins/_parameter_analysis/parameter_analysis.py
- webviz_subsurface/plugins/_parameter_analysis/utils/colors.py
- webviz_subsurface/plugins/_parameter_analysis/views/__init__.py
- webviz_subsurface/plugins/_parameter_analysis/views/main_view.py
- webviz_subsurface/plugins/_parameter_analysis/views/parameter_qc_view.py
- webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
- webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py
New plugin `ParameterAnalysis`. Dashboard to visualize parameter distributions and statistics for FMU ensembles, and to investigate parameter correlations on reservoir simulation time series data.
---
> New plugin for parameter analysis

- CHANGELOG.md
- webviz_subsurface/_datainput/opm_init_io.py
- webviz_subsurface/_datainput/pvt_data.py
- webviz_subsurface/plugins/_pvt_plot.py
> Added support for PVDO and PVTG.

- CHANGELOG.md
- webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
- webviz_subsurface/plugins/_parameter_analysis/figures/color_figure.py
- webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
- webviz_subsurface/plugins/_parameter_analysis/views/parameter_response_view.py
- webviz_subsurface/plugins/_parameter_analysis/views/selector_view.py
Several improvements to parameter analysis plugin
---
> Improvements to parameter analysis

- CHANGELOG.md
Updated changelog for version 0.1.8
Changed one url to go to the PR instead of the issue.
> Update changelog for release 0.1.8

- CHANGELOG.md
- webviz_subsurface/plugins/_well_cross_section_fmu.py
> Use user provided colors in WellCrossSectionFMU

- CHANGELOG.md
- webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
> Drop non-numeric columns in ParameterAnalysis

- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
> Remove unnecessary duplication of smry data in plugins

- setup.py
- webviz_subsurface/plugins/_subsurface_map.py
> Mute FutureWarnings from fmu-ensemble grid methods in SubsurfaceMap

- setup.py
- webviz_subsurface/plugins/_history_match.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Update doc with link to fmuobs script for observation files

- CHANGELOG.md
> Update Changelog for version 0.1.9

- CHANGELOG.md
- webviz_subsurface/plugins/_relative_permeability.py
> Oil saturation axis as option in RelativePermability plugin

- setup.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
- webviz_subsurface/plugins/_relative_permeability.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
> Comply with latest pylint

- .github/workflows/subsurface.yml
> Remove obsolete Dockerfile instruction

- setup.py
Similar to https://github.com/equinor/webviz-config/pull/409.
> Remove tests_require

- CHANGELOG.md
- webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
- webviz_subsurface/_datainput/pvt_data.py
- webviz_subsurface/_datainput/units.py
- webviz_subsurface/plugins/_pvt_plot.py
- Added phase ratio vs pressure plot
- Added density vs pressure plot
- Added unit functions and density calculations to PVT library
- Added density calculation and density and ratio unit columns to pvt_data.py
- Refactored code in _pvt_plot.py
- Added checklist for selecting plots
- Improved layout
This PR closes #533.
> Added additional plots to PVT plugin

- webviz_subsurface/_datainput/pvt_data.py
- webviz_subsurface/plugins/_pvt_plot.py
Closes #596 and closes #597. Skipping changelog as the changes are for a non-released plugin.
> Minor PVT fixes

- CHANGELOG.md
- webviz_subsurface/_datainput/fmu_input.py
- webviz_subsurface/plugins/_surface_viewer_fmu.py
> Raise descriptive error if no surfaces are found

- CHANGELOG.md
- mypy.ini
- setup.py
- tests/integration_tests/test_surface_selector.py
- tests/unit_tests/model_tests/test_surface_set_model.py
- webviz_subsurface/_datainput/fmu_input.py
- webviz_subsurface/_models/__init__.py
- webviz_subsurface/_models/surface_set_model.py
- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/plugins/_surface_viewer_fmu.py
> Shared model for surface loading and statistical calculation of surfaces

- setup.py
- webviz_subsurface/_private_plugins/tornado_plot.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_xsection.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py
- webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_response_controller.py
...which was released today (https://pypi.org/project/black/21.4b0/)
> Comply with latest black version

- .github/workflows/subsurface.yml
Followup after release of https://github.com/equinor/webviz-config/pull/318.
> Use new Docker dev. build environment variables

- CHANGELOG.md
- webviz_subsurface/plugins/_structural_uncertainty/controllers/intersection_controller.py
- webviz_subsurface/plugins/_structural_uncertainty/controllers/map_controller.py
> Load map baselayers from persisted settings

- tests/integration_tests/test_aggregated_data_example.py
- tests/integration_tests/test_raw_data_example.py
See https://github.com/plotly/dash/pull/1447#issuecomment-720737376.
> Use `dash` recommended workaround in CI integration tests

- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
Fix new pylint changes introduced in `astroid==2.57`
> `pylint` fixes to `ReservoirSimulationTimeSeries` and `ReservoirSimulationTimeSeriesOneByOne`

- .pylintrc
- CHANGELOG.md
- setup.py
- tests/integration_tests/test_parameter_filter.py
- tests/unit_tests/provider_tests/test_ensemble_table_provider.py
- webviz_subsurface/_components/parameter_filter.py
- webviz_subsurface/_models/__init__.py
- webviz_subsurface/_models/observation_model.py
- webviz_subsurface/_models/parameter_model.py
- webviz_subsurface/_providers/__init__.py
- webviz_subsurface/_providers/ensemble_table_provider.py
- webviz_subsurface/_providers/ensemble_table_provider_factory.py
- webviz_subsurface/_providers/ensemble_table_provider_impl_arrow.py
- webviz_subsurface/_providers/ensemble_table_provider_impl_inmem_parquet.py
- webviz_subsurface/_utils/perf_timer.py
- webviz_subsurface/plugins/__init__.py
- webviz_subsurface/plugins/_line_plotter_fmu/controllers/__init__.py
- webviz_subsurface/plugins/_line_plotter_fmu/controllers/build_figure.py
- webviz_subsurface/plugins/_line_plotter_fmu/controllers/update_figure_clientside.py
- webviz_subsurface/plugins/_line_plotter_fmu/figures/plotly_line_plot.py
- webviz_subsurface/plugins/_line_plotter_fmu/line_plotter_fmu.py
- webviz_subsurface/plugins/_line_plotter_fmu/views/__init__.py
- webviz_subsurface/plugins/_line_plotter_fmu/views/data_selectors_view.py
- webviz_subsurface/plugins/_line_plotter_fmu/views/plot_options_view.py
- webviz_subsurface/plugins/_line_plotter_fmu/views/plot_traces_view.py
> FMU Lineplotter

- CHANGELOG.md
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
> Support `_` in region name

- webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
- webviz_subsurface/plugins/_volumetric_analysis/figures/px_figure.py
- webviz_subsurface/plugins/_volumetric_analysis/views/selections_view.py
Fixes to VolumetricAnalysis plugin
Bugfixes:
General improvements:
---
> Fixes to `VolumetricAnalysis`

- setup.py
Relates to https://github.com/equinor/webviz-config/issues/466
> Support latest `mypy` release

- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Remove duplicate title in `ReservoirSimulationTimeSeries`

- webviz_subsurface/plugins/_well_completions.py
> Remove `wcc.Frame` wrapper from `WellCompletions`

- webviz_subsurface/_datainput/units.py
- webviz_subsurface/_datainput/xsection.py
- webviz_subsurface/_models/ensemble_model.py
- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/ert_jobs/smry2arrow.py
- webviz_subsurface/plugins/_assisted_history_matching_analysis.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_table.py
- webviz_subsurface/plugins/_parameter_analysis/models/simulation_timeseries_model.py
- webviz_subsurface/plugins/_parameter_response_correlation.py
- webviz_subsurface/plugins/_pvt_plot.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
- webviz_subsurface/plugins/_rft_plotter/rft_plotter.py
Faced two issues in `pylint`, which I disabled `pylint` for (comments added where relevant):
- https://github.com/PyCQA/pylint/issues/3045
- https://github.com/PyCQA/pylint/issues/4577
> Adhere to pylint 2.9.0

- webviz_subsurface/plugins/_well_completions.py
Moved df.DATE.unique() out of loop in get_time_series()
> Avoided recalculation of unique dates in `WellCompletions`

- CHANGELOG.md
- webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
- webviz_subsurface/plugins/_volumetric_analysis/controllers/selections_controllers.py
- webviz_subsurface/plugins/_volumetric_analysis/views/main_view.py
- webviz_subsurface/plugins/_volumetric_analysis/views/tornado_selections_view.py
This PR adds a custom mode option which allows users to freely select what response are shown in the tornadoplots in the  `VolumetricAnalysis` plugin.
> Added custom response option for tornadoplots in `VolumetricAnalysis` 

- webviz_subsurface/_datainput/surface.py
- webviz_subsurface/_models/surface_set_model.py
- webviz_subsurface/plugins/_property_statistics/utils/surface.py
- webviz_subsurface/plugins/_surface_with_grid_cross_section.py
- webviz_subsurface/plugins/_surface_with_seismic_cross_section.py
> Set required init values to `xtgeo.RegularSurface()`

- CHANGELOG.md
- webviz_subsurface/plugins/_disk_usage.py
Note that the new format is still in testing, and not fully deployed. Therefore supports the old format as well.
Should we leave it out of the changelog, considering users (hopefully) will not notice the change?
---
> Update DiskUsage to support new format

- webviz_subsurface/plugins/_parameter_analysis/controllers/parameter_qc_controller.py
- webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
- webviz_subsurface/plugins/_property_statistics/controllers/property_qc_controller.py
- webviz_subsurface/plugins/_property_statistics/models/property_statistics_model.py
- webviz_subsurface/plugins/_property_statistics/views/property_delta_view.py
PR to improve the display of tables in `ParameterAnalysis` and `PropertyStatistics`.
- Fixed issue with font sizes #727 
- Use of multi-headers and text alignment for improved readability
Before:
After:
> Table fixes to `ParameterAnalysis` and `PropertyStatistics`

- webviz_subsurface/_models/inplace_volumes_model.py
- webviz_subsurface/_models/parameter_model.py
- webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
Duplicate code lines for processing dataframes with parameter data existed in both the `VolumetricAnalysis` and the `ParameterAnalysis` plugins. The already existing `ParameterModel` also included this processing but was not used anywhere. 
This PR includes:
- adding logic for identifying if ensembles are sensitivity runs into the `ParameterModel` 
- change into using the `ParameterModel` in both the `InplaceVolumesModel` and the `ParameterAnalysis` plugin
---
> Use ParameterModel in `VolumetricAnalysis` and `ParameterAnalysis` 

- webviz_subsurface/plugins/_volumetric_analysis/views/tornado_selections_view.py
Bugfix if BULK is missing from input show only custom mode to avoid errors in the tornados.
> Bugfix for tornados in `VolumetricAnalysis` if missing BULK column 

- setup.py
- tests/integration_tests/test_raw_data_example.py
Inspired by https://github.com/plotly/dash/pull/1741.
> 🩹 for flaky test

- CHANGELOG.md
- setup.py
> Prepare for release

- .pylintrc
- webviz_subsurface/_components/color_picker.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
- webviz_subsurface/_datainput/from_timeseries_cumulatives.py
- webviz_subsurface/_datainput/pvt_data.py
- webviz_subsurface/_datainput/units.py
- webviz_subsurface/_datainput/xsection.py
- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/ert_jobs/jobs.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/horizon_uncertainty_viewer.py
- webviz_subsurface/plugins/_inplace_volumes_onebyone.py
- webviz_subsurface/plugins/_parameter_analysis/models/parameters_model.py
- webviz_subsurface/plugins/_parameter_correlation.py
- webviz_subsurface/plugins/_parameter_parallel_coordinates.py
- webviz_subsurface/plugins/_pvt_plot.py
- webviz_subsurface/plugins/_relative_permeability.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
- webviz_subsurface/plugins/_running_time_analysis_fmu.py
- webviz_subsurface/plugins/_segy_viewer.py
- webviz_subsurface/plugins/_structural_uncertainty/controllers/intersection_controller.py
- webviz_subsurface/plugins/_structural_uncertainty/controllers/uncertainty_table_controller.py
- webviz_subsurface/plugins/_tornado_plotter_fmu/tornado_plotter_fmu.py
- webviz_subsurface/plugins/_volumetric_analysis/controllers/distribution_controllers.py
- webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py
- webviz_subsurface/plugins/_well_completions.py
Similar to https://github.com/equinor/webviz-config/pull/500.
> Add `useless-suppression` to `pylint` checks

- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/plugins/_disk_usage.py
- webviz_subsurface/plugins/_history_match.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_xsection.py
- webviz_subsurface/plugins/_line_plotter_fmu/figures/plotly_line_plot.py
- webviz_subsurface/plugins/_morris_plot.py
- webviz_subsurface/plugins/_parameter_analysis/utils/colors.py
- webviz_subsurface/plugins/_property_statistics/utils/colors.py
- webviz_subsurface/plugins/_pvt_plot.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
- webviz_subsurface/plugins/_subsurface_map.py
- webviz_subsurface/plugins/_volumetric_analysis/utils/utils.py
Also created #769 as something to consider later.
> Adjust to latest `pylint`

- webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py
Minor fix after format was reset to Dash < 2.0 format in one of the files in #777
> Reset `dash` imports in `volumetric_analysis.py` to Dash 2.0 format

- tests/conftest.py
- tests/unit_tests/model_tests/test_ensemble_set_model.py
- tests/unit_tests/provider_tests/test_ensemble_table_provider.py
Related to https://github.com/equinor/webviz-subsurface-testdata/pull/105.
> Update tests based on change in testdata set

- CHANGELOG.md
- webviz_subsurface/plugins/_seismic_misfit.py
Fixed bug in doc + extended doc to explain polygon input.
For the polygon, the multi select option is now set to False as it
caused issues when combining multiple polygon-files. Also set initial
polygon value to empty for slightly better performance at start-up.
Also added minor edit to CHANGELOG.md
> Fixed doc and polygon selector

- CHANGELOG.md
- webviz_subsurface/plugins/_assisted_history_matching_analysis.py
> Fix timing issue in `AssistedHistoryMatchingAnalysis`

- CHANGELOG.md
- webviz_subsurface/_components/tornado/_tornado_bar_chart.py
- webviz_subsurface/_components/tornado/tornado_widget.py
- webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
PR with bugfixes 
improved hoverlabel for tornados and bugfixes
- show correct x value
- use senscase instead of low/high
- only show one senscase for single case sensitivities
- fix axis range bug
- fix issue in tornado when True value was selected and both high and low on one side of reference.
one bugfix in `VolumetricAnalysis`
- fix error when showing ensembles as subplot and some ensembles do not have the reference sensitivity
---
> Bugfixes and improved hoverlabels for `Tornado component`

- webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
Regression fix after #856 (non-released)
Bug occurred if a non HC-column was selected as response while looking at the total volumes. This causes the group list variable used as index in the pivot function to be empty.
> Regression fix in `VolumetricAnalysis`

- webviz_subsurface/_components/parameter_filter.py
Fix pylint error breaking master:
**Fix:**
iterating the dictionary directly instead of calling .keys()
----
Resolve issue: https://github.com/equinor/webviz-subsurface/issues/871
> Fix pylint error breaking master 

- .pylintrc
- tests/conftest.py
- webviz_subsurface/_private_plugins/surface_selector.py
- webviz_subsurface/_providers/ensemble_summary_provider/_csv_import.py
- webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider_factory.py
- webviz_subsurface/plugins/_assisted_history_matching_analysis.py
- webviz_subsurface/plugins/_disk_usage.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_table.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
This centralizes the workaround in `.pylintrc` instead of `disables` necessary throughout the code base.
> Workaround `astroid`/`pylint` bug

- webviz_subsurface/_providers/ensemble_summary_provider/_resampling.py
- webviz_subsurface/_utils/simulation_timeseries.py
- webviz_subsurface/plugins/_line_plotter_fmu/controllers/build_figure.py
- webviz_subsurface/plugins/_simulation_time_series/utils/vector_statistics.py
- webviz_subsurface/plugins/_volumetric_analysis/controllers/comparison_controllers.py
Fixed typing issues observed with numpy 1.22.0 and mypy 0.930
This PR closes #906.
> Fixed typing/mypy issues

- CHANGELOG.md
- webviz_subsurface/plugins/_property_statistics/utils/surface.py
> Handle ensembles with missing surface folders

- webviz_subsurface/_components/tornado/_tornado_bar_chart.py
---
think it isn't necessary with a changelog entry for this.
> Fix: correct labels in tornado when both cases are on same side of ref

- CHANGELOG.md
- webviz_subsurface/_components/tornado/_tornado_data.py
> Don't skip SENSNAME ref if there multiple realizations in tornado

- CHANGELOG.md
- webviz_subsurface/plugins/_reservoir_simulation_timeseries.py
> Deprecate `ReservoirSimulationTimeSeries`

- setup.py
- webviz_subsurface/_abbreviations/number_formatting.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_common.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_gas.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_oil.py
- webviz_subsurface/_datainput/eclipse_init_io/pvt_water.py
- webviz_subsurface/_models/surface_leaflet_model.py
- webviz_subsurface/plugins/_disk_usage.py
- webviz_subsurface/plugins/_horizon_uncertainty_viewer/_huv_xsection.py
- webviz_subsurface/plugins/_pvt_plot.py
- webviz_subsurface/plugins/_rft_plotter/_figures/_crossplot_figure.py
- webviz_subsurface/plugins/_rft_plotter/_figures/_map_figure.py
> Update according to new `black` version

- webviz_subsurface/_providers/ensemble_fault_polygons_provider/ensemble_fault_polygons_provider.py
- webviz_subsurface/_providers/ensemble_summary_provider/ensemble_summary_provider.py
- webviz_subsurface/_providers/ensemble_surface_provider/ensemble_surface_provider.py
- webviz_subsurface/_providers/well_provider/well_provider.py
- webviz_subsurface/_utils/simulation_timeseries.py
- webviz_subsurface/plugins/_map_viewer_fmu/callbacks.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py
- webviz_subsurface/plugins/_reservoir_simulation_timeseries_regional.py
- webviz_subsurface/plugins/_simulation_time_series/_property_serialization/graph_figure_builder_base.py
> Update according to latest `pylint`

- tests/integration_tests/plugin_tests/test_surface_with_grid_crossection.py
> Fix test input argument for `SurfaceWithGridCrossSection`

- webviz_subsurface/_models/__init__.py
- webviz_subsurface/_models/well_attributes_model.py
I have made a general class `WellAttributesModel` in the _models folder that can be re-used in many plugins.
---
> General `WellAttributesModel` class

- webviz_subsurface/plugins/_prod_misfit/_plugin.py
Closes #1008 introduced in #938.
> Fix store for `ProdMisfit`

- setup.py
- tests/unit_tests/model_tests/test_well_attributes_model.py
Tests for well_attribute_model.py.
---
> Well attribute tests with mock data

- webviz_subsurface/plugins/_structural_uncertainty/views/map_data.py
- webviz_subsurface/plugins/_swatinit_qc/_figures.py
- webviz_subsurface/plugins/_volumetric_analysis/controllers/fipfile_qc_controller.py
Fixes new `pylint` error and closes #1033.
> Fix new `pylint` and `dash` test error

- .github/workflows/subsurface.yml
- README.md
...currently only in order to smoke out which dependencies are missing wheels.
> Add Python 3.10 to CI

- .github/workflows/subsurface.yml
> Use latest official `webviz-subsurface-components` release in CI

- CHANGELOG.md
- webviz_subsurface/plugins/_parameter_response_correlation.py
Draft solution for multiple minor issues
---
- closes #909 
- closes #803 
- closes #465
- minimal fix (force all ticks) of #908
> `ParameterResponseCorrelation`: Additional options in GUI

- CHANGELOG.md
- tests/unit_tests/model_tests/test_well_attributes_model.py
- webviz_subsurface/_models/gruptree_model.py
- webviz_subsurface/_models/well_attributes_model.py
- webviz_subsurface/plugins/_well_analysis/_callbacks/well_control_callbacks.py
- webviz_subsurface/plugins/_well_analysis/_callbacks/well_overview_callbacks.py
- webviz_subsurface/plugins/_well_analysis/_ensemble_well_analysis_data.py
- webviz_subsurface/plugins/_well_analysis/_figures/well_control_figure.py
- webviz_subsurface/plugins/_well_analysis/_figures/well_overview_figure.py
- webviz_subsurface/plugins/_well_analysis/_layout/well_control_layout.py
- webviz_subsurface/plugins/_well_analysis/_layout/well_overview_layout.py
- webviz_subsurface/plugins/_well_analysis/_plugin.py
- webviz_subsurface/plugins/_well_analysis/_types.py
Several improvements to the `WellAnalysis `plugin. Fixing some unwanted bahavoir I have seen when testing it on new datasets and some new features: well attribute filter and production after date.
---
> `WellAnalysis` improvements

- CHANGELOG.md
- webviz_subsurface/plugins/_bhp_qc.py
Read data from arrow files. Related to issue #858.
Dataframe is still built in init so there may be potential for further improvements, but this should work as a first pass implementation of using arrow files instead of UNSMRY files.
> `BhpQc` - Read from `.arrow` files instead of `.UNSMRY` files

- CHANGELOG.md
- webviz_subsurface/plugins/_swatinit_qc/_figures.py
- webviz_subsurface/plugins/_swatinit_qc/_plugin.py
PR to ensure relative paths for the faultlines argument works. In addition added x-axis link for SWAT and SWATINIT plot.
> Fix relative path issue in SwatinitQC

- CHANGELOG.md
- webviz_subsurface/smry2arrow_batch.py
> removed requirement of "" around wildcarded paths in smry2arrow_batch

- CHANGELOG.md
- webviz_subsurface/_providers/ensemble_summary_provider/_provider_impl_arrow_lazy.py
- webviz_subsurface/_providers/ensemble_summary_provider/_provider_impl_arrow_presampled.py
> Fixed issue with ambigious truth of `pd.Series` in `EnsembleSummaryProvider`

- webviz_subsurface/_datainput/pvt_data.py
- webviz_subsurface/plugins/_disk_usage.py
> Fix `pandas` `FutureWarnings`

- webviz_subsurface/plugins/_well_analysis/_plugin.py
- webviz_subsurface/plugins/_well_analysis/_views/_well_overview_view/_view.py
We think this will fix the conversion error in `callback_typecheck`.
---
> Fix `ConversionError` in `callback_typecheck`.

- CHANGELOG.md
- webviz_subsurface/_datainput/relative_permeability.py
- webviz_subsurface/_utils/colors.py
- webviz_subsurface/plugins/_relative_permeability.py
> Option to plot only pyscal data in `RelativePermeability` plugin

- CHANGELOG.md
- webviz_subsurface/plugins/_map_viewer_fmu/callbacks.py
- webviz_subsurface/plugins/_map_viewer_fmu/map_viewer_fmu.py
> Add surface download in MapViewer plugin

- CHANGELOG.md
- webviz_subsurface/_providers/ensemble_surface_provider/surface_server.py
> Give linux group write permission to cached files

- .github/workflows/subsurface.yml
- webviz_subsurface/_providers/ensemble_grid_provider/grid_viz_service.py
> Fix incorrect type in grid_viz_service

- CHANGELOG.md
Changelog entry to https://github.com/equinor/webviz-subsurface/pull/1229.
---
> Changelog entry to #1229

- CHANGELOG.md
- webviz_subsurface/plugins/_volumetric_analysis/views/comparison_layout.py
Add changelog entry for #1266.
Also reduced the line lengths of the radio button text, to avoid text wrapping. They were a bit long after the move to selections.
> Add changelog entry for waterfall plot

- .github/workflows/subsurface.yml
Resolves #1276
This PR updates the GitHub-actions used in the workflow to their newest versions.
---
> Update GitHub actions dependencies

- setup.py
- webviz_subsurface/_datainput/from_timeseries_cumulatives.py
- webviz_subsurface/_datainput/history_match.py
- webviz_subsurface/_datainput/pvt_data.py
- webviz_subsurface/_providers/ensemble_summary_provider/_dataframe_utils.py
- webviz_subsurface/plugins/_history_match.py
- webviz_subsurface/plugins/_parameter_response_correlation.py
- webviz_subsurface/plugins/_running_time_analysis_fmu.py
Resolves https://github.com/equinor/webviz-subsurface/issues/1288
Build using pandas 2.0.2/2.2.2:
https://github.com/equinor/webviz-subsurface/actions/runs/9110545525
Build using pandas 1.5.3:
https://github.com/equinor/webviz-subsurface/actions/runs/9110407584
> Provide pandas 2 compatibility

- .github/workflows/subsurface.yml
- README.md
> Support Python 3.12

- CHANGELOG.md
- setup.py
- webviz_subsurface/_components/tornado/_tornado_data.py
- webviz_subsurface/plugins/_volumetric_analysis/controllers/tornado_controllers.py
PR to add a column with mean value for mc type sensitivities to the tornado table in `VolumetricAnalysis`
> Add mean in tornado table in 'VolumetricAnalysis'

- webviz_subsurface/_providers/ensemble_surface_provider/surface_array_server.py
- webviz_subsurface/_providers/ensemble_surface_provider/surface_image_server.py
...as it might give problems with the new Radix blob storage driver.
> Remove surface cache file mode

- webviz_subsurface/_models/parameter_model.py
> Fix FutureWarning - cast to dtype
